// Generated by scripts/fetchAdvancedF2l.ts. Do not edit by hand.
import type { AdvancedF2lCase } from "./f2lTrainingCases";

export const ADVANCED_F2L_SOURCE = {"url":"https://speedcubedb.com/a/3x3/AdvancedF2L","fetched":"2026-09-30","cases":54,"algorithms":379} as const;

export const ADVANCED_F2L_CASES: readonly AdvancedF2lCase[] = [
  {
    "name": "AF2L 1",
    "group": "Trapped Corner",
    "variants": {
      "FR": {
        "setup": "B U B' R U R'",
        "algorithms": [
          "R U' R' y R U' R'",
          "R U' R' f R' f'",
          "R U' R' U R2 F R F' R"
        ]
      },
      "FL": {
        "setup": "R U R' U' L' U L",
        "algorithms": [
          "L' U' L U R U' R'",
          "M F' M'",
          "L' R U' R' L",
          "R L' U' L R'"
        ]
      },
      "BL": {
        "setup": "F U F' L U L'",
        "algorithms": [
          "L U' L' y L U' L'",
          "L U' L' y' R U' R'"
        ]
      },
      "BR": {
        "setup": "L U L' U' R' U R",
        "algorithms": [
          "R' U' R U L U' L'",
          "L R' U' R L'",
          "M' f' E"
        ]
      }
    }
  },
  {
    "name": "AF2L 2",
    "group": "Trapped Corner",
    "variants": {
      "FR": {
        "setup": "L F' U2' F L'",
        "algorithms": [
          "L F' U2 F L'",
          "F' L U2 L' F"
        ]
      },
      "FL": {
        "setup": "B U B' L' U L",
        "algorithms": [
          "L' U' L y R U' R'",
          "L' U' L Fw R' Fw'"
        ]
      },
      "BL": {
        "setup": "R U R' U L U L'",
        "algorithms": [
          "L U' L' U' R U' R'",
          "L U' L' R U2 R'"
        ]
      },
      "BR": {
        "setup": "F U F' R' U R",
        "algorithms": [
          "R' U' R F U' F'",
          "R' U' R y' R U' R'"
        ]
      }
    }
  },
  {
    "name": "AF2L 3",
    "group": "Trapped Corner",
    "variants": {
      "FR": {
        "setup": "L F' L' F U' R U R'",
        "algorithms": [
          "R U' R' U F' r U r'",
          "R U' R' U F' L F L'",
          "R U' F R' U R F' R'"
        ]
      },
      "FL": {
        "setup": "L U2' L2' U L",
        "algorithms": [
          "L' U' L2 U2 L'"
        ]
      },
      "BL": {
        "setup": "B U B' U B' U B",
        "algorithms": [
          "y R' U' R U' R U' R'",
          "y R' U' R2 U2 R'",
          "y' L' U' L2 U2 L'"
        ]
      },
      "BR": {
        "setup": "R U2' R2' U R",
        "algorithms": [
          "R' U' R2 U2 R'"
        ]
      }
    }
  },
  {
    "name": "AF2L 4",
    "group": "Trapped Corner",
    "variants": {
      "FR": {
        "setup": "R' U2' R U' R' F R F'",
        "algorithms": [
          "F R' F' R U R' U2 R"
        ]
      },
      "FL": {
        "setup": "R U' R' U2' F U' F'",
        "algorithms": [
          "F U F' U2 R U R'",
          "y' R U R' U2 y R U R'"
        ]
      },
      "BL": {
        "setup": "F U' F' U2' L U' L'",
        "algorithms": [
          "L U L' y U2 L U L'",
          "L U L' U2 F U F'",
          "L U L' y' U2 R U R'"
        ]
      },
      "BR": {
        "setup": "L U' L' U R' U' R U2'",
        "algorithms": [
          "U2 R' U R U' L U L'"
        ]
      }
    }
  },
  {
    "name": "AF2L 5",
    "group": "Trapped Corner",
    "variants": {
      "FR": {
        "setup": "L U' L' R U2' R' U",
        "algorithms": [
          "U' R U2 M' B r'",
          "U' R U2 R' L U L'"
        ]
      },
      "FL": {
        "setup": "R' U2' R F' L F L'",
        "algorithms": [
          "r U' r' F R' U2 R",
          "L F' L' F R' U2 R"
        ]
      },
      "BL": {
        "setup": "R U' R' U' L U' L'",
        "algorithms": [
          "L U L' U R U R'"
        ]
      },
      "BR": {
        "setup": "F U' F' U2' R' U' R U2'",
        "algorithms": [
          "U2 R' U R U2 F U F'",
          "U2 R' U R y' U2 R U R'"
        ]
      }
    }
  },
  {
    "name": "AF2L 6",
    "group": "Trapped Corner",
    "variants": {
      "FR": {
        "setup": "F U' F' R U' R'",
        "algorithms": [
          "R U R' F U F'",
          "R U R' b L b'",
          "R U R' y L U L'"
        ]
      },
      "FL": {
        "setup": "L U' L' U' L' U' L U2'",
        "algorithms": [
          "U2 L' U L U L U L'"
        ]
      },
      "BL": {
        "setup": "B U' B' L U' L'",
        "algorithms": [
          "L U L' f R f'",
          "L U L' y' L U L'"
        ]
      },
      "BR": {
        "setup": "R U' R' B U' B'",
        "algorithms": [
          "y R U R' F U F'",
          "f R f' R U R'"
        ]
      }
    }
  },
  {
    "name": "AF2L 7",
    "group": "Trapped Corner",
    "variants": {
      "FR": {
        "setup": "B U' B' F' U F U",
        "algorithms": [
          "y U' L' U' L R U R'"
        ]
      },
      "FL": {
        "setup": "R U R' L' U' L U",
        "algorithms": [
          "U' L' U L R U' R'"
        ]
      },
      "BL": {
        "setup": "F U F' B' U' B U",
        "algorithms": [
          "y' U' L' U L R U' R'"
        ]
      },
      "BR": {
        "setup": "L U L' R' U' R U",
        "algorithms": [
          "U' R' U R L U' L'"
        ]
      }
    }
  },
  {
    "name": "AF2L 8",
    "group": "Trapped Corner",
    "variants": {
      "FR": {
        "setup": "L U' L' U2' F R' F' R U",
        "algorithms": [
          "U' R' F R F' U2 L U L'",
          "R U' R' U L U' L' U L U L'"
        ]
      },
      "FL": {
        "setup": "F R' U R2' U' R' U2' F'",
        "algorithms": [
          "F U2 R U R2 U' R F'"
        ]
      },
      "BL": {
        "setup": "R U2' R' B' U' B U",
        "algorithms": [
          "y' U' L' U L y' L U2 L'",
          "y U' R' U R y' R U2 R'"
        ]
      },
      "BR": {
        "setup": "F U2' F' R' U' R U",
        "algorithms": [
          "U' R' U R d' L U' L'",
          "U' R' U R U2 F' r U r'",
          "U' R' U R F U2 F'"
        ]
      }
    }
  },
  {
    "name": "AF2L 9",
    "group": "Trapped Corner",
    "variants": {
      "FR": {
        "setup": "F U' F' U F' U2' F U'",
        "algorithms": [
          "y' U R' U2 R U' R U R'",
          "y U L' U2 L U' L U L'"
        ]
      },
      "FL": {
        "setup": "L U L' U2' L' U' L U",
        "algorithms": [
          "U' L' U L U2 L U' L'",
          "U' L' U L U' L U2 L'"
        ]
      },
      "BL": {
        "setup": "L' B' L B L' B L U'",
        "algorithms": [
          "U L' B' L B' L' B L"
        ]
      },
      "BR": {
        "setup": "R U' R' U R' U2' R U'",
        "algorithms": [
          "U R' U2 R U' R U R'"
        ]
      }
    }
  },
  {
    "name": "AF2L 10",
    "group": "Trapped Edge",
    "variants": {
      "FR": {
        "setup": "R' U R2' U' R' U",
        "algorithms": [
          "U' R U R2 U' R"
        ]
      },
      "FL": {
        "setup": "F' U F2' U' F' U",
        "algorithms": [
          "U' F U F2 U' F",
          "y' U' R U R2 U' R",
          "y U' L U L2 U' L"
        ]
      },
      "BL": {
        "setup": "L' U L2' U' L' U",
        "algorithms": [
          "U' L U L2 U' L"
        ]
      },
      "BR": {
        "setup": "B' U B2' U' B' U",
        "algorithms": [
          "y U' R U R2 U' R",
          "y' U' L U L2 U' L"
        ]
      }
    }
  },
  {
    "name": "AF2L 11",
    "group": "Trapped Edge",
    "variants": {
      "FR": {
        "setup": "L U L' R U R' U",
        "algorithms": [
          "U' R U' R' L U' L'",
          "U' R U' M' B' r'",
          "U' R U' R' U L U2 L'"
        ]
      },
      "FL": {
        "setup": "R' U R L' U L U",
        "algorithms": [
          "U' L' U' L R' U' R"
        ]
      },
      "BL": {
        "setup": "R U R' L U L' U",
        "algorithms": [
          "U' L U' L' R U' R'"
        ]
      },
      "BR": {
        "setup": "L' U L R' U R U",
        "algorithms": [
          "U' R' U' R L' U' L"
        ]
      }
    }
  },
  {
    "name": "AF2L 12",
    "group": "Trapped Edge",
    "variants": {
      "FR": {
        "setup": "L' U L U2' R U' R' U",
        "algorithms": [
          "U' R U R' U2 L' U' L",
          "F U' F' U2 R U' R' L' U' L"
        ]
      },
      "FL": {
        "setup": "L U' L2' U L2' U' L' U",
        "algorithms": [
          "U' L U L2 U' L2 U L'"
        ]
      },
      "BL": {
        "setup": "R' U R L U L' U2'",
        "algorithms": [
          "U2 L U' L' R' U' R"
        ]
      },
      "BR": {
        "setup": "R U' R2' U R2' U2' R' U2'",
        "algorithms": [
          "U2 R U2 R2 U' R2 U R'"
        ]
      }
    }
  },
  {
    "name": "AF2L 13",
    "group": "Trapped Edge",
    "variants": {
      "FR": {
        "setup": "B U B' R U R' U' R U R' U'",
        "algorithms": [
          "U R U' R' U R U' R' f R' f'",
          "U R U' R' U R U' R' y' L U' L'"
        ]
      },
      "FL": {
        "setup": "F' U2' L' U' L2' F L' U",
        "algorithms": [
          "U' L F' L2 U L U2 F",
          "U' L F' L' F U2 R U R'"
        ]
      },
      "BL": {
        "setup": "F U' F' U2' L' B L B' U",
        "algorithms": [
          "y' U' L F' L' F U2 R U R'"
        ]
      },
      "BR": {
        "setup": "B' U B R B' R' B U'",
        "algorithms": [
          "y U R' F R F' R' U' R"
        ]
      }
    }
  },
  {
    "name": "AF2L 14",
    "group": "Trapped Edge",
    "variants": {
      "FR": {
        "setup": "L U' L' U' R' F R F' U",
        "algorithms": [
          "U' F R' F' R U L U L'"
        ]
      },
      "FL": {
        "setup": "R2' D' F2' D R2' U2'",
        "algorithms": [
          "U2 R2 D' F2 D R2",
          "U2 R2 u' R2 u R2"
        ]
      },
      "BL": {
        "setup": "R2' D B2' D' R2' U2'",
        "algorithms": [
          "U2 R2 D B2 D' R2",
          "U2 R2 u R2 u' R2"
        ]
      },
      "BR": {
        "setup": "L2' D' B2' D L2' U2'",
        "algorithms": [
          "U2 L2 D' B2 D L2",
          "U2 r2 U' F2 U r2",
          "U2 L2 u' L2 u L2"
        ]
      }
    }
  },
  {
    "name": "AF2L 15",
    "group": "Trapped Edge",
    "variants": {
      "FR": {
        "setup": "F U2' R U R2' F' R U'",
        "algorithms": [
          "U R' F R2 U' R' U2 F'",
          "U R' F R F' U2 L' U' L"
        ]
      },
      "FL": {
        "setup": "L U' L' F' L F L' U",
        "algorithms": [
          "U' L F' L' F L U L'"
        ]
      },
      "BL": {
        "setup": "B U' B' L' B L B' U",
        "algorithms": [
          "y' U' L F' L' F L U L'"
        ]
      },
      "BR": {
        "setup": "R U2' B U B2' R' B U'",
        "algorithms": [
          "y U R' F R2 U' R' U2 F'",
          "y U R' F R F' U2 L' U' L"
        ]
      }
    }
  },
  {
    "name": "AF2L 16",
    "group": "Trapped Edge",
    "variants": {
      "FR": {
        "setup": "R B' R' B R U R' U",
        "algorithms": [
          "U' R U' R' r' U' R U M'",
          "U' R U' R' B' R B R'"
        ]
      },
      "FL": {
        "setup": "R' D' F D R U",
        "algorithms": [
          "U' R' D' F' D R",
          "U' R' u' R' u R"
        ]
      },
      "BL": {
        "setup": "L F' L' F L U L' U",
        "algorithms": [
          "U' L U' L' F' L F L'"
        ]
      },
      "BR": {
        "setup": "B' U B U' R' U R U",
        "algorithms": [
          "U' R' U' R y U R' U' R",
          "U' R' U' R U f' L' f"
        ]
      }
    }
  },
  {
    "name": "AF2L 17",
    "group": "Trapped Edge",
    "variants": {
      "FR": {
        "setup": "R B' U B R' U2'",
        "algorithms": [
          "U2 R B' U' B R'",
          "y U2 F R' U' R F'",
          "U2 l U' F' U l'"
        ]
      },
      "FL": {
        "setup": "F R' U R F' U2'",
        "algorithms": [
          "U2 F R' U' R F'",
          "U2 F U' F' U R' U' R"
        ]
      },
      "BL": {
        "setup": "L F' U F L' U2'",
        "algorithms": [
          "U2 L F' U' F L'"
        ]
      },
      "BR": {
        "setup": "F R' U' R U F' U2'",
        "algorithms": [
          "U2 F U' R' U R F'"
        ]
      }
    }
  },
  {
    "name": "AF2L 18",
    "group": "Trapped Edge",
    "variants": {
      "FR": {
        "setup": "F U2' F' R U R' U",
        "algorithms": [
          "U' R U' R' F U2 F'",
          "U' R U' R' U2 F' L F L'"
        ]
      },
      "FL": {
        "setup": "L U2' L' F U F' U",
        "algorithms": [
          "U' F U' F' L U2 L'"
        ]
      },
      "BL": {
        "setup": "R' F R' F' R2' L U L' U",
        "algorithms": [
          "U' L U' L' d' R U' R'",
          "U' L U' L' R2 F R F' R",
          "U' L U' L' U' f R' f'",
          "U' L U' L' y R U2 R'"
        ]
      },
      "BR": {
        "setup": "F' U F U R' U R U",
        "algorithms": [
          "U' R' U' R d' L' U' L",
          "U' R' U' R U' F' U' F"
        ]
      }
    }
  },
  {
    "name": "AF2L 19",
    "group": "Trapped Edge",
    "variants": {
      "FR": {
        "setup": "B U' B' U' R U' R' U'",
        "algorithms": [
          "U R U R' U y R U R'",
          "U R U R' U f R f'"
        ]
      },
      "FL": {
        "setup": "R' F R2' U' R' U2' F' U'",
        "algorithms": [
          "U F U2 R U R2 F' R",
          "U L' U L F' U2 F"
        ]
      },
      "BL": {
        "setup": "F U' F' U' L U' L' U'",
        "algorithms": [
          "U L U L' d R U R'",
          "U L U L' U F U F'"
        ]
      },
      "BR": {
        "setup": "B' U2' B R' U' R U'",
        "algorithms": [
          "U R' U R d L' U L",
          "U R' U R U f' L f",
          "U R' U R y R' U2 R",
          "U R' U R y' L' U2 L"
        ]
      }
    }
  },
  {
    "name": "AF2L 20",
    "group": "Trapped Edge",
    "variants": {
      "FR": {
        "setup": "L U' L' R U' R' U'",
        "algorithms": [
          "U R U R' L U L'",
          "U R U M' B r'"
        ]
      },
      "FL": {
        "setup": "R' U' R L' U' L U'",
        "algorithms": [
          "U L' U L R' U R"
        ]
      },
      "BL": {
        "setup": "R U' R' L U' L' U'",
        "algorithms": [
          "U L U L' R U R'"
        ]
      },
      "BR": {
        "setup": "L' U' L R' U' R U'",
        "algorithms": [
          "U R' U R L' U L"
        ]
      }
    }
  },
  {
    "name": "AF2L 21",
    "group": "Trapped Edge",
    "variants": {
      "FR": {
        "setup": "L D F' D' L' U'",
        "algorithms": [
          "U L u L u' L'",
          "U L D F D' L'"
        ]
      },
      "FL": {
        "setup": "L' B L B' L' U' L U'",
        "algorithms": [
          "U L' U L R B L' B' M' x'",
          "U L' U L B L' B' L"
        ]
      },
      "BL": {
        "setup": "B U' B' U L U' L' U'",
        "algorithms": [
          "U L U L' U' f R f'",
          "U L U L' y' U' L U L'"
        ]
      },
      "BR": {
        "setup": "F D R' D' F' U'",
        "algorithms": [
          "U F D R D' F'",
          "d R u R u' R'"
        ]
      }
    }
  },
  {
    "name": "AF2L 22",
    "group": "Trapped Edge",
    "variants": {
      "FR": {
        "setup": "R' U' R2' U R'",
        "algorithms": [
          "R U' R2 U R"
        ]
      },
      "FL": {
        "setup": "R L' U2' L R'",
        "algorithms": [
          "R L' U2 L R'"
        ]
      },
      "BL": {
        "setup": "L' U' L2' U L'",
        "algorithms": [
          "L U' L2 U L"
        ]
      },
      "BR": {
        "setup": "L R' U2' R L'",
        "algorithms": [
          "L R' U2 R L'"
        ]
      }
    }
  },
  {
    "name": "AF2L 23",
    "group": "Trapped Edge",
    "variants": {
      "FR": {
        "setup": "L F' U' F L'",
        "algorithms": [
          "L F' U F L'",
          "y' F R' U R F'"
        ]
      },
      "FL": {
        "setup": "B U B' U' L' U' L",
        "algorithms": [
          "r' F U' R U M'",
          "L' U L y' U L U' L'",
          "L' U L y U R U' R'"
        ]
      },
      "BL": {
        "setup": "F' L U L' F",
        "algorithms": [
          "F' L U' L' F",
          "L U' L' d' L' U L",
          "L U' L' y' U' R' U R"
        ]
      },
      "BR": {
        "setup": "F R' U' R F'",
        "algorithms": [
          "F R' U R F'",
          "R' U R y' U R U' R'",
          "R' U R y U L U' L'"
        ]
      }
    }
  },
  {
    "name": "AF2L 24",
    "group": "Trapped Edge",
    "variants": {
      "FR": {
        "setup": "L' U' L U2' R U R'",
        "algorithms": [
          "R U' R' U2 L' U L"
        ]
      },
      "FL": {
        "setup": "L U L2' U' L",
        "algorithms": [
          "L' U L2 U' L'"
        ]
      },
      "BL": {
        "setup": "R' L U2' L' R",
        "algorithms": [
          "R' L U2 L' R"
        ]
      },
      "BR": {
        "setup": "R U R2' U' R",
        "algorithms": [
          "R' U R2 U' R'"
        ]
      }
    }
  },
  {
    "name": "AF2L 25",
    "group": "Both Pieces Trapped",
    "variants": {
      "FR": {
        "setup": "R' U2' R U' F R' F' R",
        "algorithms": [
          "R' F R F' U R' U2 R"
        ]
      },
      "FL": {
        "setup": "R' F R2' U R2' F' R",
        "algorithms": [
          "R' F R2 U' R2 F' R",
          "F R U' R2 F' R"
        ]
      },
      "BL": {
        "setup": "F U F' U L U' L'",
        "algorithms": [
          "L U L' y' U' R U' R'",
          "L U L' F U2 F'"
        ]
      },
      "BR": {
        "setup": "y f R' f' U R U R' y'",
        "algorithms": [
          "y R U' R' U' f R f'"
        ]
      }
    }
  },
  {
    "name": "AF2L 26",
    "group": "Both Pieces Trapped",
    "variants": {
      "FR": {
        "setup": "L R U2' R' L'",
        "algorithms": [
          "L R U2 R' L'"
        ]
      },
      "FL": {
        "setup": "R' U2' R U' L' U L",
        "algorithms": [
          "L' U' L U R' U2 R"
        ]
      },
      "BL": {
        "setup": "R U2' R' U L U' L'",
        "algorithms": [
          "L U L' U' R U2 R'"
        ]
      },
      "BR": {
        "setup": "L' U' L U2' R' U R",
        "algorithms": [
          "R' U' R U2 L' U L"
        ]
      }
    }
  },
  {
    "name": "AF2L 27",
    "group": "Both Pieces Trapped",
    "variants": {
      "FR": {
        "setup": "F R U' R2' F' R",
        "algorithms": [
          "R' F R2 U R' F'"
        ]
      },
      "FL": {
        "setup": "B' U' B U' L' U L",
        "algorithms": [
          "L' U' L U y' L' U L",
          "L' U' L y R' U2 R"
        ]
      },
      "BL": {
        "setup": "B U B' U' L U' L'",
        "algorithms": [
          "L U L' U y R U' R'",
          "L U L' B' R B R'"
        ]
      },
      "BR": {
        "setup": "F' U' F U' R' U R",
        "algorithms": [
          "R' U' R U y L' U L",
          "R' U' R F' U2 F"
        ]
      }
    }
  },
  {
    "name": "AF2L 28",
    "group": "Both Pieces Trapped",
    "variants": {
      "FR": {
        "setup": "R' U R U R' U R2' U R'",
        "algorithms": [
          "R U' R2 U' R U' R' U' R"
        ]
      },
      "FL": {
        "setup": "R U R' U' R U' R' U' L' U' L",
        "algorithms": [
          "L' U L U R U R' U R U' R'",
          "F U' R U R' U R U' R' F' R U' R'"
        ]
      },
      "BL": {
        "setup": "L' U L U L' U L2' U L'",
        "algorithms": [
          "L U' L2 U' L U' L' U' L"
        ]
      },
      "BR": {
        "setup": "L U L' U' L U' L' U' R' U' R",
        "algorithms": [
          "R' U R U L U L' U L U' L'"
        ]
      }
    }
  },
  {
    "name": "AF2L 29",
    "group": "Both Pieces Trapped",
    "variants": {
      "FR": {
        "setup": "F' L U' L' U L' U' L U' F",
        "algorithms": [
          "F' U L' U L U' L U L' F"
        ]
      },
      "FL": {
        "setup": "B2' L' B' L B' L' U' L",
        "algorithms": [
          "L' U L B L' B L B2",
          "L' U L y' L U L' U L U' L'",
          "L' U' L U L' U L f R f'",
          "L' U L y R U R' U R U' R'"
        ]
      },
      "BL": {
        "setup": "F' U F U' F' U' F L U L'",
        "algorithms": [
          "L U' L' y' R' U R U R' U' R",
          "L U' L' y L' U L U L' U' L"
        ]
      },
      "BR": {
        "setup": "F2' R' F' R F' R' U' R",
        "algorithms": [
          "R' U R F R' F R F2",
          "R' U R y' R U R' U R U' R'"
        ]
      }
    }
  },
  {
    "name": "AF2L 30",
    "group": "Both Pieces Trapped",
    "variants": {
      "FR": {
        "setup": "L' U L U2' R U R' U R U R'",
        "algorithms": [
          "R U' R' U' R U' R' U2 L' U' L",
          "M F M' U L' U L U' L' U L"
        ]
      },
      "FL": {
        "setup": "L U L' U' L U' L' U L' U' L",
        "algorithms": [
          "L' U L U' L U L' U L U' L'"
        ]
      },
      "BL": {
        "setup": "R' U R U' R' U' R U L U L'",
        "algorithms": [
          "L U' L' U' R' U R U R' U' R"
        ]
      },
      "BR": {
        "setup": "R U R' U' R U' R' U R' U' R",
        "algorithms": [
          "R' U R U' R U R' U R U' R'"
        ]
      }
    }
  },
  {
    "name": "AF2L 31",
    "group": "Both Pieces Trapped",
    "variants": {
      "FR": {
        "setup": "R' U R U' R U R' U R U' R'",
        "algorithms": [
          "R U R' U' R U' R' U R' U' R",
          "R U' R' U R' U' R U' R' U R"
        ]
      },
      "FL": {
        "setup": "R U' R' U' R U' R2' F R U R' F' R",
        "algorithms": [
          "R' F R U' R' F' R2 U R' U R U R'"
        ]
      },
      "BL": {
        "setup": "L' U' L U L' U L U' L U L'",
        "algorithms": [
          "L U' L' U L' U' L U' L' U L"
        ]
      },
      "BR": {
        "setup": "L U' L' U L U L' U' R' U' R",
        "algorithms": [
          "R' U R U L U' L' U' L U L'"
        ]
      }
    }
  },
  {
    "name": "AF2L 32",
    "group": "Both Pieces Trapped",
    "variants": {
      "FR": {
        "setup": "B' U' B U B' U B R U R'",
        "algorithms": [
          "R U R' U' R U' R' f' L' f",
          "R U' R' U f' U' L' U L' f",
          "R U' R' y R' U' R U' R' U R"
        ]
      },
      "FL": {
        "setup": "F R' U R U' R U R' U F'",
        "algorithms": [
          "F U' R U' R' U R' U' R F'"
        ]
      },
      "BL": {
        "setup": "F' U' F U F' U F L U L'",
        "algorithms": [
          "L U' L' y L' U' L U' L' U L",
          "L U' L' y' R' U' R U' R' U R",
          "L U L' U' L U' L' b' R' b",
          "L U' L' F' L F' L' F2"
        ]
      },
      "BR": {
        "setup": "F U' F' U F U F' R' U' R",
        "algorithms": [
          "R' U R U' L' U L d' L U L'",
          "R' U R y L U' L' U' L U L'",
          "R' U R y' R U' R' U' R U R'"
        ]
      }
    }
  },
  {
    "name": "AF2L 33",
    "group": "Both Pieces Trapped",
    "variants": {
      "FR": {
        "setup": "L' U' L U L' U L U R U R'",
        "algorithms": [
          "R U' R' U' L' U' L U' L' U L",
          "R U R' U' R U' R' U' L' U' L"
        ]
      },
      "FL": {
        "setup": "L U' L' U' L U' L2' U' L",
        "algorithms": [
          "L' U L2 U L' U L U L'"
        ]
      },
      "BL": {
        "setup": "R' U' R U R' U R U L U L'",
        "algorithms": [
          "L U' L' U' R' U' R U' R' U R"
        ]
      },
      "BR": {
        "setup": "R U' R2' U' R U' R' U' R",
        "algorithms": [
          "R' U R U R' U R2 U R'"
        ]
      }
    }
  },
  {
    "name": "AF2L 34",
    "group": "Both Pieces Trapped",
    "variants": {
      "FR": {
        "setup": "F' R' U R U R' U' R F",
        "algorithms": [
          "F' R' U R U' R' U' R F"
        ]
      },
      "FL": {
        "setup": "F' U F U F' U' F U' L' U L",
        "algorithms": [
          "L' U' L U y' R' U R U' R' U' R",
          "L' U' L d R' U R U' R' U' R"
        ]
      },
      "BL": {
        "setup": "F U F' U' L U' L' U L U L'",
        "algorithms": [
          "L U' L' U' L U L' U y L U' L'",
          "L U' L' U' L U L' F' L F L'"
        ]
      },
      "BR": {
        "setup": "B' U B U B' U' B U' R' U R",
        "algorithms": [
          "R' U' R y U R' U R U' R' U' R"
        ]
      }
    }
  },
  {
    "name": "AF2L 35",
    "group": "Both Pieces Trapped",
    "variants": {
      "FR": {
        "setup": "L U L' R U' R' U R U R'",
        "algorithms": [
          "R U' R' U' R U R' L U' L'",
          "R U' R' U' R U M' B' r'"
        ]
      },
      "FL": {
        "setup": "R' U R U R' U' R L' U L",
        "algorithms": [
          "L' U' L R' U R U' R' U' R"
        ]
      },
      "BL": {
        "setup": "R U R' L U' L' U L U L'",
        "algorithms": [
          "L U' L' U' L U L' R U' R'"
        ]
      },
      "BR": {
        "setup": "L' U' L U L' U2' L U' R' U' R",
        "algorithms": [
          "R' U R U L' U2 L U' L' U L"
        ]
      }
    }
  },
  {
    "name": "AF2L 36",
    "group": "Both Pieces Trapped",
    "variants": {
      "FR": {
        "setup": "F U2' R U' R' U R U R2' F' R",
        "algorithms": [
          "R' F R2 U' R' U' R U R' U2 F'",
          "R' F R F' U2 L' U L U' L' U' L"
        ]
      },
      "FL": {
        "setup": "B' U' B U B' U2' B L' U' L",
        "algorithms": [
          "L' U L y R' U2 R U' R' U R",
          "L' U L y' L' U2 L U' L' U L"
        ]
      },
      "BL": {
        "setup": "B U2' B' L U' L' U L U L'",
        "algorithms": [
          "L U' L' U' L U L' y' L U2 L'"
        ]
      },
      "BR": {
        "setup": "F' U' F U F' U2' F R' U' R",
        "algorithms": [
          "R' U R y' R' U2 R U' R' U R",
          "R' U R2 U' R2 F R F' R U' R'"
        ]
      }
    }
  },
  {
    "name": "AF2L 37",
    "group": "Both Pieces Trapped",
    "variants": {
      "FR": {
        "setup": "F' R' U R U' R' U2' R U F",
        "algorithms": [
          "F' U' R' U2 R U R' U' R F"
        ]
      },
      "FL": {
        "setup": "F' U F U' F' U2' F L' U L",
        "algorithms": [
          "L' U' L y' R' U2 R U R' U' R",
          "L' U' L y L' U2 L U L' U' L"
        ]
      },
      "BL": {
        "setup": "F U F' U' F U2' F' L U L'",
        "algorithms": [
          "L U' L' y L U2 L' U L U' L'"
        ]
      },
      "BR": {
        "setup": "B' U2' B R' U R U' R' U' R",
        "algorithms": [
          "R' U R U R' U' R y R' U2 R"
        ]
      }
    }
  },
  {
    "name": "AF2L 38",
    "group": "Both Pieces Trapped",
    "variants": {
      "FR": {
        "setup": "L U2' L' R U2' R' U' R U R'",
        "algorithms": [
          "R U' R' U R U2 R' L U2 L'",
          "R U' R' U R U2 R' U' L U' L'"
        ]
      },
      "FL": {
        "setup": "R' U' R L' U L U' L' U' L",
        "algorithms": [
          "L' U L U L' U' L R' U R"
        ]
      },
      "BL": {
        "setup": "R U R' U' R U2' R' U L U L'",
        "algorithms": [
          "L U' L' U' R U2 R' U R U' R'"
        ]
      },
      "BR": {
        "setup": "L' U L U' L' U2' L U R' U R",
        "algorithms": [
          "R' U' R U' L' U2 L U L' U' L"
        ]
      }
    }
  },
  {
    "name": "AF2L 39",
    "group": "Both Pieces Trapped",
    "variants": {
      "FR": {
        "setup": "F U' F' U' F U F' U R U' R'",
        "algorithms": [
          "R U R' d' L U' L' U L U L'",
          "R U R' U' y' R U' R' U R U R'",
          "R U R' L' U L U' L F' L' F L' U L"
        ]
      },
      "FL": {
        "setup": "B' U B U' B' U2' B U2' L' U L",
        "algorithms": [
          "L' U' L y U2 R' U2 R U R' U' R",
          "L' U' L y' U2 L' U2 L U L' U' L"
        ]
      },
      "BL": {
        "setup": "B U B' U' B U2' B' U2' L U L'",
        "algorithms": [
          "L U' L' y' U2 L U2 L' U L U' L'"
        ]
      },
      "BR": {
        "setup": "F' U F U' F' U2' F U2' R' U R",
        "algorithms": [
          "R' U' R y' U2 R' U2 R U R' U' R",
          "R' U' R U d R' U2 R U R' U' R"
        ]
      }
    }
  },
  {
    "name": "AF2L 40",
    "group": "Both Pieces Trapped",
    "variants": {
      "FR": {
        "setup": "R' U2' R U' R' U2' R2' U R'",
        "algorithms": [
          "R U' R2 U2 R U R' U2 R",
          "R U' R2 U2 R U2 R' U R"
        ]
      },
      "FL": {
        "setup": "R U R' U2' R U R' U' R U R' L' U L",
        "algorithms": [
          "L' U' L R U' R' U R U' R' U2 R U' R'",
          "L' U' L R' U2 R2 U R2 U R"
        ]
      },
      "BL": {
        "setup": "L' U' L U2' L' U2' L2' U L'",
        "algorithms": [
          "L U' L2 U2 L U2 L' U L",
          "L U' L2 U2 L U L' U2 L"
        ]
      },
      "BR": {
        "setup": "L U L' U2' L U2' L' U2' R' U' R",
        "algorithms": [
          "R' U R U2 L U2 L' U2 L U' L'"
        ]
      }
    }
  },
  {
    "name": "AF2L 41",
    "group": "Both Pieces Trapped",
    "variants": {
      "FR": {
        "setup": "F' L U' L2' U2' L U2' F",
        "algorithms": [
          "F' U2 L' U2 L2 U L' F",
          "R U' R' y U' R' U2 R U R' U2 R"
        ]
      },
      "FL": {
        "setup": "F R' U R2' U2' R' U2' F'",
        "algorithms": [
          "F U2 R U2 R2 U' R F'",
          "L' U L U2 r U2 R2 U' R2 U' r'"
        ]
      },
      "BL": {
        "setup": "F' U F U' R U2' R' L U' L'",
        "algorithms": [
          "L U L' R U2 R' y' U R' U' R",
          "L U L' R U2 R' U F' U' F"
        ]
      },
      "BR": {
        "setup": "F U' F' U L' U2' L R' U R",
        "algorithms": [
          "R' U' R L' U2 L y U' L U L'",
          "R' U' R L' U2 L U' F U F'"
        ]
      }
    }
  },
  {
    "name": "AF2L 42",
    "group": "Both Pieces Trapped",
    "variants": {
      "FR": {
        "setup": "F U F' U2' F U2' F2' U' F",
        "algorithms": [
          "y' R' U R2 U2 R' U2 R U' R'",
          "y' R' U R2 U2 R' U' R U2 R'"
        ]
      },
      "FL": {
        "setup": "L U L' U2' L U2' L2' U' L",
        "algorithms": [
          "L' U L2 U2 L' U2 L U' L'",
          "L' U L2 U2 L' U' L U2 L'"
        ]
      },
      "BL": {
        "setup": "R U R2' U R2' U2' R' L U' L'",
        "algorithms": [
          "L U L' R U2 R2 U' R2 U' R'"
        ]
      },
      "BR": {
        "setup": "F R' F' R U' R U2' R2' U' R",
        "algorithms": [
          "R' U R2 U2 R' U R' F R F'",
          "R' U R2 U2 R' U2 R U' R'"
        ]
      }
    }
  },
  {
    "name": "AF2L 1a",
    "group": "Trapped Corner",
    "variants": {
      "FR": {
        "setup": "R' U R U R U R' U2'",
        "algorithms": [
          "U2 R U' R' U' R' U' R"
        ]
      },
      "FL": {
        "setup": "F' U F L' U L",
        "algorithms": [
          "L' U' L y' R' U' R",
          "L' U' L F' U' F"
        ]
      },
      "BL": {
        "setup": "L' U L B' U B",
        "algorithms": [
          "y R' U' R y R' U' R",
          "f' L' f L' U' L",
          "y' L' U' L F' U' F",
          "y' L' U' L y L' U' L"
        ]
      },
      "BR": {
        "setup": "B' U B R' U R",
        "algorithms": [
          "R' U' R y R' U' R",
          "R' U' R f' L' f"
        ]
      }
    }
  },
  {
    "name": "AF2L 2a",
    "group": "Trapped Corner",
    "variants": {
      "FR": {
        "setup": "L U2' L' F R' F' R",
        "algorithms": [
          "R' F R F' L U2 L'",
          "R' F R F' U' L U' L'"
        ]
      },
      "FL": {
        "setup": "R' U R U L' U L",
        "algorithms": [
          "L' U' L U' R' U' R"
        ]
      },
      "BL": {
        "setup": "F' U F U B' U B",
        "algorithms": [
          "y' L' U' L U' R' U' R",
          "y R' U' R U' L' U' L"
        ]
      },
      "BR": {
        "setup": "L' U L U R' U R",
        "algorithms": [
          "R' U' R U' L' U' L"
        ]
      }
    }
  },
  {
    "name": "AF2L 3a",
    "group": "Trapped Corner",
    "variants": {
      "FR": {
        "setup": "F U' R U R2' F' R",
        "algorithms": [
          "R' F R2 U' R' U F'",
          "R' F R F' d R' F R F'"
        ]
      },
      "FL": {
        "setup": "B' U B U2' L' U L",
        "algorithms": [
          "L' U' L y U2 R' U' R",
          "L' U' L y' U2 L' U' L",
          "L' U' L U2 f' L' f"
        ]
      },
      "BL": {
        "setup": "R' U R U2' B' U B",
        "algorithms": [
          "f' L' f U2 R' U' R",
          "y R' U' R y' U2 R' U' R",
          "y' L' U' L y U2 R' U' R"
        ]
      },
      "BR": {
        "setup": "F' U F U2' R' U R",
        "algorithms": [
          "R' U' R U2 F' U' F",
          "R' U' R y U2 L' U' L",
          "R' U' R y' U2 R' U' R"
        ]
      }
    }
  },
  {
    "name": "AF2L 4a",
    "group": "Trapped Corner",
    "variants": {
      "FR": {
        "setup": "R' U2' R2' U' R' U'",
        "algorithms": [
          "U R U R2 U2 R"
        ]
      },
      "FL": {
        "setup": "F' U' F U2' L' U' L U'",
        "algorithms": [
          "U L' U L y' U2 R' U R",
          "U L' U L y U2 L' U L",
          "U L' U L U' F R' F' R"
        ]
      },
      "BL": {
        "setup": "L' U2' L2' U' L' U'",
        "algorithms": [
          "U L U L2 U2 L"
        ]
      },
      "BR": {
        "setup": "B' U2' B U' R' U' R U'",
        "algorithms": [
          "U R' U R y U R' U2 R",
          "U R' U R y U2 R' U R",
          "U R' U R y' U2 L' U L"
        ]
      }
    }
  },
  {
    "name": "AF2L 5a",
    "group": "Trapped Corner",
    "variants": {
      "FR": {
        "setup": "R B' U2' B R' U'",
        "algorithms": [
          "U l U' F2 U l'",
          "U R B' U2 B R'"
        ]
      },
      "FL": {
        "setup": "R' U2' R L' U' L U'",
        "algorithms": [
          "U L' U L R' U2 R"
        ]
      },
      "BL": {
        "setup": "F' U2' F B' U' B U'",
        "algorithms": [
          "y' U L' U L R' U2 R",
          "y U R' U R L' U2 L"
        ]
      },
      "BR": {
        "setup": "L' U2' L R' U' R U'",
        "algorithms": [
          "U R' U R L' U2 L"
        ]
      }
    }
  },
  {
    "name": "AF2L 6a",
    "group": "Trapped Corner",
    "variants": {
      "FR": {
        "setup": "R L' U' L R' U'",
        "algorithms": [
          "U R L' U L R'",
          "U R U R' U' L' U L",
          "U M F M'"
        ]
      },
      "FL": {
        "setup": "B' U' B L' U' L U'",
        "algorithms": [
          "U L' U L f' L f",
          "U L' U L y R' U R"
        ]
      },
      "BL": {
        "setup": "L R' U' R L' U'",
        "algorithms": [
          "U L R' U R L'",
          "U L R' U L' R"
        ]
      },
      "BR": {
        "setup": "B F' U' F B' U'",
        "algorithms": [
          "U S R S'",
          "y U R L' U L R'",
          "y' U L R' U R L'"
        ]
      }
    }
  },
  {
    "name": "AF2L 7a",
    "group": "Trapped Corner",
    "variants": {
      "FR": {
        "setup": "R' U' R U2' R U R' U2'",
        "algorithms": [
          "U2 R U' R' U2 R' U R",
          "U2 R U' R' U R' U2 R"
        ]
      },
      "FL": {
        "setup": "F' U' F U2' F U F' U2'",
        "algorithms": [
          "y' U2 R U' R' U2 R' U R",
          "y' U2 R U' R' U R' U2 R"
        ]
      },
      "BL": {
        "setup": "L' U' L U2' L U L' U2'",
        "algorithms": [
          "U2 L U' L' U2 L' U L",
          "U2 L U' L' U L' U2 L"
        ]
      },
      "BR": {
        "setup": "B' U' B U2' B U B' U2'",
        "algorithms": [
          "y U2 R U' R' U2 R' U R",
          "y' U2 L U' L' U2 L' U L"
        ]
      }
    }
  },
  {
    "name": "AF2L 8a",
    "group": "Trapped Corner",
    "variants": {
      "FR": {
        "setup": "B' U B R U2' R'",
        "algorithms": [
          "R U2 R' f' L' f",
          "R U2 R' y R' U' R"
        ]
      },
      "FL": {
        "setup": "R' U R U2' F' L F L' U2'",
        "algorithms": [
          "U2 L F' L' F U2 R' U' R"
        ]
      },
      "BL": {
        "setup": "F' U2' F L U L' U2'",
        "algorithms": [
          "U2 L U' L' y L' U2 L",
          "U2 L U' L' y' R' U2 R"
        ]
      },
      "BR": {
        "setup": "L' D U L U L' D' L U'",
        "algorithms": [
          "U L' D L U' L' U' D' L"
        ]
      }
    }
  },
  {
    "name": "AF2L 9a",
    "group": "Trapped Corner",
    "variants": {
      "FR": {
        "setup": "L' U' L R U R' U2'",
        "algorithms": [
          "U2 R U' R' L' U L"
        ]
      },
      "FL": {
        "setup": "B' U' B F U F' U2'",
        "algorithms": [
          "y U2 L U' L' R' U R",
          "y' U2 R U' R' L' U L"
        ]
      },
      "BL": {
        "setup": "R' U' R L U L' U2'",
        "algorithms": [
          "U2 L U' L' R' U R"
        ]
      },
      "BR": {
        "setup": "F' U' F B U B' U2'",
        "algorithms": [
          "y U2 R U' R' L' U L",
          "y' U2 L U' L' R' U R"
        ]
      }
    }
  },
  {
    "name": "AF2L 10a",
    "group": "Trapped Edge",
    "variants": {
      "FR": {
        "setup": "f R f' U' R U R' U",
        "algorithms": [
          "U' R U' R' U f R' f'",
          "U' R U' R' d L U' L'"
        ]
      },
      "FL": {
        "setup": "L' F' U F L U",
        "algorithms": [
          "y' U' F' R' U' R F"
        ]
      },
      "BL": {
        "setup": "F' D' L D F U",
        "algorithms": [
          "U' F' D' L' D F"
        ]
      },
      "BR": {
        "setup": "R' B' U B R U",
        "algorithms": [
          "y U' F' R' U' R F"
        ]
      }
    }
  },
  {
    "name": "AF2L 11a",
    "group": "Trapped Edge",
    "variants": {
      "FR": {
        "setup": "B' U B U R U' R' U",
        "algorithms": [
          "U' R U R' y' U' L' U' L",
          "U' R U R' U' f' L' f",
          "U' R U R' d' R' U' R",
          "U' R U R' U' y2 F' U' F"
        ]
      },
      "FL": {
        "setup": "R' U R U F U' F' U",
        "algorithms": [
          "U' F U F' U' R' U' R"
        ]
      },
      "BL": {
        "setup": "F' U F U L U' L' U",
        "algorithms": [
          "U' L U L' U' F' U' F",
          "U' L U L' y U' L' U' L",
          "U' L U L' y' U' R' U' R"
        ]
      },
      "BR": {
        "setup": "F R' U' R U F' U2'",
        "algorithms": [
          "y U2 L U' F' U F L'"
        ]
      }
    }
  },
  {
    "name": "AF2L 12a",
    "group": "Trapped Edge",
    "variants": {
      "FR": {
        "setup": "F U2' F' R U R' U",
        "algorithms": [
          "U' R U' R' U2 F' r U r'",
          "U' R U' R' y L U2 L'",
          "U' F' U2 L' U' L2 F L'",
          "U' R U' R' y' U' R U' R'"
        ]
      },
      "FL": {
        "setup": "B' U B L' U2' L U'",
        "algorithms": [
          "U L' U2 L y' L' U' L",
          "U L' U2 L y R' U' R"
        ]
      },
      "BL": {
        "setup": "B U2' B' L U L' U",
        "algorithms": [
          "U' L U' L' y' L U2 L'"
        ]
      },
      "BR": {
        "setup": "F' U F R' U2' R U'",
        "algorithms": [
          "U R' U2 R y' R' U' R",
          "U R' U2 R y L' U' L"
        ]
      }
    }
  }
];
