// Generated by scripts/fetchAdvancedF2l.ts. Do not edit by hand.
import type { AdvancedF2lCase } from "./f2lTrainingCases";

export const ADVANCED_F2L_SOURCE = {"url":"https://speedcubedb.com/a/3x3/AdvancedF2L","fetched":"2026-09-30","cases":54,"algorithms":667} as const;

export const ADVANCED_F2L_CASES: readonly AdvancedF2lCase[] = [
  {
    "name": "AF2L 1",
    "group": "Trapped Corner",
    "setup": "S R S'",
    "canonicalTarget": "BR",
    "algorithms": {
      "FR": [
        "L' U' L U R U' R'",
        "M F' M'",
        "L' R U' R' L",
        "R L' U' L R'"
      ],
      "FL": [
        "S' L' S",
        "L U' L' y L U' L'",
        "y' L' U' L U R U' R'",
        "L U' L' y' R U' R'"
      ],
      "BL": [
        "R' U' R U L U' L'",
        "L R' U' R L'",
        "M' f' E",
        "y R U' R2 F' U' F R"
      ],
      "BR": [
        "S R' S'",
        "R U' R' y R U' R'",
        "R U' R' f R' f'",
        "R U' R' U R2 F R F' R"
      ]
    }
  },
  {
    "name": "AF2L 2",
    "group": "Trapped Corner",
    "setup": "L U2' L' R U R'",
    "canonicalTarget": "BL",
    "algorithms": {
      "FR": [
        "l U' F2 U l'",
        "L U' L' U' R U' R'",
        "L U' L' R U2 R'",
        "y' r' U F2 U' r"
      ],
      "FL": [
        "F R' U2 R F'",
        "R' U' R F U' F'",
        "R' U' R y' R U' R'",
        "y R U' R' L U2 L'"
      ],
      "BL": [
        "L F' U2 F L'",
        "R U' R' L U2 L'",
        "L R U' R' U2 L'",
        "F' L U2 L' F"
      ],
      "BR": [
        "y' R U' R' L U2 L'",
        "r' U F2 U' r",
        "L' U' L y R U' R'",
        "L' U' L Fw R' Fw'"
      ]
    }
  },
  {
    "name": "AF2L 3",
    "group": "Trapped Corner",
    "setup": "L F' L' F U' R U R'",
    "canonicalTarget": "FL",
    "algorithms": {
      "FR": [
        "R' U' R2 U2 R'",
        "R' U2 R2 U' R'"
      ],
      "FL": [
        "R U' R' U F' r U r'",
        "R U' R' U F' L F L'",
        "y' R' U2 R2 U' R'",
        "R U' F R' U R F' R'"
      ],
      "BL": [
        "L' U' L2 U2 L'",
        "L' U2 L2 U' L'"
      ],
      "BR": [
        "y R' U' R U' R U' R'",
        "L U' L' y' U2 L U' L'",
        "y R' U' R2 U2 R'",
        "y' L' U' L2 U2 L'"
      ]
    }
  },
  {
    "name": "AF2L 4",
    "group": "Trapped Corner",
    "setup": "Fw R' Fw' U2' R U' R'",
    "canonicalTarget": "BR",
    "algorithms": {
      "FR": [
        "U2 L' U L U' R U R'",
        "F U F' U2 R U R'",
        "U' F U' R U R2 F' R",
        "y' R U R' U2 y R U R'"
      ],
      "FL": [
        "L U L' y U2 L U L'",
        "B L' B' L U L' U2 L",
        "L U L' U2 F U F'",
        "L U L' y' U2 R U R'"
      ],
      "BL": [
        "U2 R' U R U' L U L'"
      ],
      "BR": [
        "F R' F' R U R' U2 R",
        "R U R' U2 f R f'",
        "R U R' U2 S U' R' U R S'",
        "y U2 L' U L U' R U R'"
      ]
    }
  },
  {
    "name": "AF2L 5",
    "group": "Trapped Corner",
    "setup": "L U' L' U' R U' R'",
    "canonicalTarget": "BL",
    "algorithms": {
      "FR": [
        "L U L' U R U R'"
      ],
      "FL": [
        "U2 R' U R U2 F U F'",
        "y R U R' U L U L'",
        "U2 R' U R y' U2 R U R'"
      ],
      "BL": [
        "R U R' U L U L'",
        "U' R U2 M' B r'",
        "U' R U2 R' L U L'",
        "y U2 L' U L U2 f R f'"
      ],
      "BR": [
        "r U' r' F R' U2 R",
        "L F' L' F R' U2 R",
        "y' R U R' U L U L'",
        "y' U' R U2 R' L U L'"
      ]
    }
  },
  {
    "name": "AF2L 6",
    "group": "Trapped Corner",
    "setup": "F U' F' R U' R'",
    "canonicalTarget": "FL",
    "algorithms": {
      "FR": [
        "U2 R' U R U R U R'",
        "y R U R' F U F'",
        "f R f' R U R'"
      ],
      "FL": [
        "R U R' F U F'",
        "F R' F' R L' U L",
        "R U R' b L b'",
        "R U R' y L U L'"
      ],
      "BL": [
        "U2 L' U L U L U L'",
        "F U F' L U L'",
        "L F' L' S' L f",
        "L' U L U L' U' L2 U L'"
      ],
      "BR": [
        "y U2 R' U R U R U R'",
        "L U L' f R f'",
        "L U L' y' L U L'",
        "B L' B' L R' U R"
      ]
    }
  },
  {
    "name": "AF2L 7",
    "group": "Trapped Corner",
    "setup": "Fw R' Fw' U F R' F' R U",
    "canonicalTarget": "BR",
    "algorithms": {
      "FR": [
        "U' L' U L R U' R'",
        "U' L' U' L R U R'"
      ],
      "FL": [
        "y' U' L' U L R U' R'",
        "U' f' r' D r S",
        "U' f' L' F L S"
      ],
      "BL": [
        "U' R' U R L U' L'",
        "U' R' U' R L U L'"
      ],
      "BR": [
        "U' F' U' f R S'",
        "y U' L' U' L R U R'",
        "R U' R' U' R U' R' f R f'",
        "U' R' F R F' U' f R f'"
      ]
    }
  },
  {
    "name": "AF2L 8",
    "group": "Trapped Corner",
    "setup": "L U' L' U2' F R' F' R U",
    "canonicalTarget": "BL",
    "algorithms": {
      "FR": [
        "R D' R' U R U D R'",
        "U' f' L' f U' R U R'",
        "y' U' L' U L y' L U2 L'",
        "y U' R' U R y' R U2 R'"
      ],
      "FL": [
        "U' R' U R d' L U' L'",
        "U' R' U R U2 F' r U r'",
        "U' R' U' R d' L U L'",
        "U' R' U R F U2 F'"
      ],
      "BL": [
        "U' F' U2 L U L' F",
        "U' R' F R F' U2 L U L'",
        "y' U R' U2 R F U F'",
        "R U' R' U L U' L' U L U L'"
      ],
      "BR": [
        "U L' U2 L f R f'",
        "F U2 R U R2 U' R F'",
        "U' L' U L y' L U2 L'",
        "U' L' U' L d' R U R'"
      ]
    }
  },
  {
    "name": "AF2L 9",
    "group": "Trapped Corner",
    "setup": "F U' F' U' F R' F' R U",
    "canonicalTarget": "FL",
    "algorithms": {
      "FR": [
        "U R' U2 R U' R U R'",
        "U' R' U R U2 R U' R'"
      ],
      "FL": [
        "y' U R' U2 R U' R U R'",
        "U R' F' R F' R' F R",
        "U R' F R F' R U' R' U' L' U' L",
        "y U L' U2 L U' L U L'"
      ],
      "BL": [
        "U L' U2 L U' L U L'",
        "U' L' U L U2 L U' L'",
        "y' U' R' F R F' U F U F'",
        "U' L' U L U' L U2 L'"
      ],
      "BR": [
        "U L' B' L B' L' B L",
        "y' U' L' U L U2 L U' L'"
      ]
    }
  },
  {
    "name": "AF2L 10",
    "group": "Trapped Edge",
    "setup": "R' U R2' U' R' U",
    "canonicalTarget": "BR",
    "algorithms": {
      "FR": [
        "U' F U F2 U' F",
        "U' L F2 L' F2",
        "y' U' R U R2 U' R",
        "y U' L U L2 U' L"
      ],
      "FL": [
        "U' L U L2 U' L"
      ],
      "BL": [
        "R' U R L U' L' U L U L'",
        "y U' R U R2 U' R",
        "y' U' L U L2 U' L"
      ],
      "BR": [
        "U' R U R2 U' R",
        "y L' U L R U' R' U R U R'",
        "U2 R U R' U2 R' U R",
        "y U' L F2 L' F2"
      ]
    }
  },
  {
    "name": "AF2L 11",
    "group": "Trapped Edge",
    "setup": "L U L' R U R' U",
    "canonicalTarget": "BL",
    "algorithms": {
      "FR": [
        "U' L U' L' R U' R'",
        "y U' R' U' L' U' L R"
      ],
      "FL": [
        "U' R' U' R L' U' L"
      ],
      "BL": [
        "U' R U' R' L U' L'",
        "U' R U' M' B' r'",
        "U' R U' R' U L U2 L'"
      ],
      "BR": [
        "U' L' U' L R' U' R",
        "U L' U2 L U R' U' R",
        "U' L' U' R' U' R L"
      ]
    }
  },
  {
    "name": "AF2L 12",
    "group": "Trapped Edge",
    "setup": "L' U L U2' R U' R' U",
    "canonicalTarget": "FL",
    "algorithms": {
      "FR": [
        "U2 R U2 R2 U' R2 U R'",
        "U' R S' U2 S R'",
        "U' R U R2 U' R2 U R'"
      ],
      "FL": [
        "U2 R U R' L' U L",
        "U' R U R2 F R U F'",
        "U' R U R' U2 L' U' L",
        "F U' F' U2 R U' R' L' U' L"
      ],
      "BL": [
        "U' L U L2 U' L2 U L'",
        "L' U' L U' L' U L U' L U2 L'",
        "U' L S U2 S' L'",
        "y' U' R U R2 F R U R' F' R"
      ],
      "BR": [
        "U2 L U' L' R' U' R",
        "U' L U L' U2 R' U' R",
        "U2 L U L' R' U R"
      ]
    }
  },
  {
    "name": "AF2L 13",
    "group": "Trapped Edge",
    "setup": "R' U R F R' F' R U'",
    "canonicalTarget": "BR",
    "algorithms": {
      "FR": [
        "U' L F' L2 U L U2 F",
        "d R' F R F' R' U' R",
        "U' L F' L' F U2 R U R'"
      ],
      "FL": [
        "y' U' L F' L' F U2 R U R'",
        "U r' U L U' x L' U' L",
        "U L U' L' U S' L' S"
      ],
      "BL": [
        "y U R' F R F' R' U' R",
        "U' l U' R' U x U2 L U L'",
        "U' R B' R2 U R U2 R B R'"
      ],
      "BR": [
        "U R' F R F' R' U' R",
        "U R U' R' U S R' S'",
        "U R U' R' U R U' R' f R' f'",
        "U R U' R' U R U' R' y' L U' L'"
      ]
    }
  },
  {
    "name": "AF2L 14",
    "group": "Trapped Edge",
    "setup": "Fw' L Fw U F R' F' R U'",
    "canonicalTarget": "BL",
    "algorithms": {
      "FR": [
        "L U L' U' L U L' U R U R'",
        "U2 R2 D B2 D' R2",
        "U2 R2 u R2 u' R2",
        "U L U' L' U L U' L' R U2 R'"
      ],
      "FL": [
        "R' U' R U R' U' R U' L' U' L",
        "U2 L2 D' B2 D L2",
        "U2 r2 U' F2 U r2",
        "U2 L2 u' L2 u L2"
      ],
      "BL": [
        "U' F R' F' R U L U L'",
        "U2 r2 U B2 U' r2",
        "U2 L2 u L2 u' L2",
        "U R U' R' U R U' R' L U2 L'"
      ],
      "BR": [
        "U2 R2 D' F2 D R2",
        "U' L' U L U' L' U L R' U2 R",
        "U2 R2 u' R2 u R2",
        "L' U' L U L' U' L U' R' U' R"
      ]
    }
  },
  {
    "name": "AF2L 15",
    "group": "Trapped Edge",
    "setup": "L' U L U2' F R' F' R U'",
    "canonicalTarget": "FL",
    "algorithms": {
      "FR": [
        "U' R' U R U' S R S'",
        "y U R' F R2 U' R' U2 F'",
        "y U R' F R F' U2 L' U' L"
      ],
      "FL": [
        "U R' F R2 U' R' U2 F'",
        "U R' F R F' U2 L' U' L",
        "R U R' U' R U R' F U F'",
        "U R' F R2 U' R' U2 R' F' R"
      ],
      "BL": [
        "U' L F' L' F L U L'",
        "U' L' U L U' S' L S"
      ],
      "BR": [
        "y' U' L F' L' F L U L'",
        "U' R' U' R2 u R u' R'"
      ]
    }
  },
  {
    "name": "AF2L 16",
    "group": "Trapped Edge",
    "setup": "F' R' U R F U",
    "canonicalTarget": "BR",
    "algorithms": {
      "FR": [
        "U' R' D' F' D R",
        "U' R' u' R' u R",
        "U' L' F' U' F L",
        "U' r' D' F' D r"
      ],
      "FL": [
        "U' L U' L' F' L F L'",
        "d' L' u' L' u L"
      ],
      "BL": [
        "U' R' U' R y U R' U' R",
        "U' R' U' R U f' L' f",
        "U' L' u' L' u L",
        "y' U' F' D' L' D F"
      ],
      "BR": [
        "U' F' R' U' R F",
        "d' R' u' R' u R",
        "U' R U' R' r' U' R U M'",
        "U' R U' R' B' R B R'"
      ]
    }
  },
  {
    "name": "AF2L 17",
    "group": "Trapped Edge",
    "setup": "Fw' L Fw U R U' R' U",
    "canonicalTarget": "BL",
    "algorithms": {
      "FR": [
        "U2 R d' R' U R F'",
        "U2 L F' U' F L'"
      ],
      "FL": [
        "U2 f R' f' U L' U' L",
        "U2 f U' R' U f'",
        "U2 F U' R' U R F'",
        "U2 f R f' L' U2 L"
      ],
      "BL": [
        "U2 R B' U' B R'",
        "y U2 F R' U' R F'",
        "U' R U R' U' f' L' f",
        "U2 l U' F' U l'"
      ],
      "BR": [
        "U2 F R' U' R F'",
        "U2 F U' F' U R' U' R",
        "U2 L F' L' F R' U' R",
        "U2 F U F' R' U2 R"
      ]
    }
  },
  {
    "name": "AF2L 18",
    "group": "Trapped Edge",
    "setup": "L' U L U F' U F U",
    "canonicalTarget": "FL",
    "algorithms": {
      "FR": [
        "U R' U2 R F' U' F",
        "U' R' U' R d' L' U' L",
        "U' f R' f' U' R U' R'",
        "U' R' U' R U' F' U' F"
      ],
      "FL": [
        "U F' U2 F L' U' L",
        "U r' F' D' F D r",
        "U' R U' R' F U2 F'",
        "U' R U' R' U2 F' L F L'"
      ],
      "BL": [
        "U' L' U' L d' R' U' R",
        "U L' U2 L f' L' f",
        "U' F U' F' L U2 L'",
        "F U R U' R' U' R U' R' L U2 L' F'"
      ],
      "BR": [
        "U' L U' L' d' R U' R'",
        "U' L U' L' R2 F R F' R",
        "U' L U' L' U' f R' f'",
        "U' L U' L' y R U2 R'"
      ]
    }
  },
  {
    "name": "AF2L 19",
    "group": "Trapped Edge",
    "setup": "f R' f' U' R U' R' U'",
    "canonicalTarget": "BR",
    "algorithms": {
      "FR": [
        "U' F U2 F' R U R'",
        "U' R U F U' F' R'",
        "U F U2 R U R2 F' R",
        "U L' U L F' U2 F"
      ],
      "FL": [
        "U' L U2 L' F U F'",
        "U L U L' d R U R'",
        "U f' L f L' U2 L",
        "U L U L' U F U F'"
      ],
      "BL": [
        "U R' U R d L' U L",
        "U R' U R U f' L f",
        "U R' U R y R' U2 R",
        "U R' U R y' L' U2 L"
      ],
      "BR": [
        "U' R U2 R' f R f'",
        "R' F R F' R U2 R2 U R",
        "U R U R' U y R U R'",
        "U R U R' U f R f'"
      ]
    }
  },
  {
    "name": "AF2L 20",
    "group": "Trapped Edge",
    "setup": "L U' L' R U' R' U'",
    "canonicalTarget": "BL",
    "algorithms": {
      "FR": [
        "U L U L' R U R'",
        "U' L U2 L' U' R U R'"
      ],
      "FL": [
        "U R' U R L' U L"
      ],
      "BL": [
        "U R U R' L U L'",
        "U' R U2 R' U' L U L'",
        "U R U M' B r'"
      ],
      "BR": [
        "U L' U L R' U R"
      ]
    }
  },
  {
    "name": "AF2L 21",
    "group": "Trapped Edge",
    "setup": "R F U' F' R' U'",
    "canonicalTarget": "FL",
    "algorithms": {
      "FR": [
        "U F D R D' F'",
        "U R' U R U' F' U F",
        "d R u R u' R'",
        "U R' U R F R' F' R"
      ],
      "FL": [
        "U R F U F' R'",
        "U L u L u' L'",
        "U L D F D' L'",
        "U R U R' U' F U F'"
      ],
      "BL": [
        "U F L U L' F'",
        "U L' U L R B L' B' M' x'",
        "d L u L u' L'",
        "U L' U L B L' B' L"
      ],
      "BR": [
        "U L U L' U' f R f'",
        "U R u R u' R'",
        "U' L U2 L' y' U2 L U L'",
        "U L U L' y' U' L U L'"
      ]
    }
  },
  {
    "name": "AF2L 22",
    "group": "Trapped Edge",
    "setup": "R' U' R2' U R'",
    "canonicalTarget": "BR",
    "algorithms": {
      "FR": [
        "R L' U2 L R'",
        "L' U L U2 R U' R'",
        "F2 R' F2 R"
      ],
      "FL": [
        "L U' L2 U L"
      ],
      "BL": [
        "L R' U2 R L'"
      ],
      "BR": [
        "R U' R2 U R",
        "y M F2 M'",
        "S R2 S'",
        "R U2 R2 U2 R"
      ]
    }
  },
  {
    "name": "AF2L 23",
    "group": "Trapped Edge",
    "setup": "L F' U' F L'",
    "canonicalTarget": "BL",
    "algorithms": {
      "FR": [
        "F' L U' L' F",
        "R u R' U R u' R'",
        "L U' L' d' L' U L",
        "L U' L' y' U' R' U R"
      ],
      "FL": [
        "F R' U R F'",
        "R' U R y' U R U' R'",
        "R' U R y U L U' L'",
        "L' u' L U' L' u L"
      ],
      "BL": [
        "L F' U F L'",
        "y' F R' U R F'",
        "l F' U L' U' M'",
        "R U2 R' y' L' U L"
      ],
      "BR": [
        "R' F U' F' R",
        "r' F U' R U M'",
        "L' U L y' U L U' L'",
        "L' U L y U R U' R'"
      ]
    }
  },
  {
    "name": "AF2L 24",
    "group": "Trapped Edge",
    "setup": "L' R U2' R' L",
    "canonicalTarget": "FL",
    "algorithms": {
      "FR": [
        "R' U R2 U' R'",
        "R' U2 R2 U2 R'",
        "R2 F R2 F'"
      ],
      "FL": [
        "R U' R' U2 L' U L",
        "M F2 M'",
        "F2 r U2 r'",
        "U F r U2 r' F'"
      ],
      "BL": [
        "L' U L2 U' L'"
      ],
      "BR": [
        "R' L U2 L' R",
        "L U' L' U2 R' U R"
      ]
    }
  },
  {
    "name": "AF2L 25",
    "group": "Both Pieces Trapped",
    "setup": "Fw R' Fw' U R U R'",
    "canonicalTarget": "BR",
    "algorithms": {
      "FR": [
        "R' F R2 U' R2 F' R",
        "R' F R2 U R' F' R U2 R'",
        "F R U' R2 F' R",
        "L F' L' F R U' R'"
      ],
      "FL": [
        "L U L' y' U' R U' R'",
        "L U' L' d' L U L'",
        "L U L' F U2 F'",
        "L U' L' U' F U F'"
      ],
      "BL": [
        "y R U' R' U' f R f'",
        "R' U R d' R' U' R",
        "R' U' R l U L' U' M'"
      ],
      "BR": [
        "R' F R F' U R' U2 R",
        "F' U R' U2 R F",
        "R U' R' U' f R f'",
        "R U R' U' B U' B'"
      ]
    }
  },
  {
    "name": "AF2L 26",
    "group": "Both Pieces Trapped",
    "setup": "R L U2' L' R'",
    "canonicalTarget": "BL",
    "algorithms": {
      "FR": [
        "L U L' U' R U2 R'",
        "R L U2 L' R'"
      ],
      "FL": [
        "R' U' R U2 L' U L",
        "R' L' U2 L R"
      ],
      "BL": [
        "L R U2 R' L'",
        "R U' R' U2 L U L'",
        "R U2 R' U L U' L'",
        "R U R' U' L U2 L'"
      ],
      "BR": [
        "L' U' L U R' U2 R",
        "L' R' U2 R L"
      ]
    }
  },
  {
    "name": "AF2L 27",
    "group": "Both Pieces Trapped",
    "setup": "r U' r' F R U' R'",
    "canonicalTarget": "FL",
    "algorithms": {
      "FR": [
        "F' R' U2 R U' F",
        "R' U' R U y L' U L",
        "R' U R d R' U' R",
        "R' U' R F' U2 F"
      ],
      "FL": [
        "R' F R2 U R' F'",
        "R U2 R' F U' F'",
        "R' F R2 U R2 F' R",
        "R U R' F' r U r'"
      ],
      "BL": [
        "L' U L U f' L' f",
        "L' U' L U y' L' U L",
        "L' U' L y R' U2 R",
        "F U' L U2 L' F'"
      ],
      "BR": [
        "L U L' U y R U' R'",
        "L U L' B' R B R'",
        "L U' L' U f R f'"
      ]
    }
  },
  {
    "name": "AF2L 28",
    "group": "Both Pieces Trapped",
    "setup": "R' U R2 U' R' D U' R' U R D'",
    "canonicalTarget": "BR",
    "algorithms": {
      "FR": [
        "L' U L U R U R' U R U' R'",
        "F U' R U R' U R U' R' F' R U' R'"
      ],
      "FL": [
        "L U' L2 U' L U' L' U' L"
      ],
      "BL": [
        "R' U R U L U L' U L U' L'"
      ],
      "BR": [
        "R U' R2 U' R U' R' U' R",
        "R U' R' U' R U' R2 U' R",
        "r U' r' U2 r U r' d' R U R'",
        "u R U R' u' R U' R2 U R"
      ]
    }
  },
  {
    "name": "AF2L 29",
    "group": "Both Pieces Trapped",
    "setup": "Fw' L Fw U R U R' U R U R'",
    "canonicalTarget": "BL",
    "algorithms": {
      "FR": [
        "f' L f R U R2 F R F'",
        "L U' L' U' L U' L' d' L' U' L",
        "L U' L' y' R' U R U R' U' R",
        "L U' L' y L' U L U L' U' L"
      ],
      "FL": [
        "R' U R F R' F R F2",
        "R' U R y' R U R' U R U' R'"
      ],
      "BL": [
        "F' U L' U L U' L U L' F",
        "R U' R' U' R U' R' d' R' U' R",
        "R U' R' y R' U R U R' U' R",
        "F' U F L U L' U L U' L'"
      ],
      "BR": [
        "L' U L B L' B L B2",
        "L' U L y' L U L' U L U' L'",
        "L' U' L U L' U L f R f'",
        "L' U L y R U R' U R U' R'"
      ]
    }
  },
  {
    "name": "AF2L 30",
    "group": "Both Pieces Trapped",
    "setup": "L' U L U2' R U R' U R U R'",
    "canonicalTarget": "FL",
    "algorithms": {
      "FR": [
        "R' U R U' R U R' U R U' R'"
      ],
      "FL": [
        "R U' R' U' L' U L U L' U' L",
        "R U' R' U' R U' R' U2 L' U' L",
        "M F M' U L' U L U' L' U L",
        "r U' r' U2 r U r' d R U R'"
      ],
      "BL": [
        "L' U L U' L U L' U L U' L'"
      ],
      "BR": [
        "L U' L' U' R' U R U R' U' R"
      ]
    }
  },
  {
    "name": "AF2L 31",
    "group": "Both Pieces Trapped",
    "setup": "R' U' R U R' U R U' R U R'",
    "canonicalTarget": "BR",
    "algorithms": {
      "FR": [
        "R' F R U' R' F' R2 U R' U R U R'",
        "L' U L U L' U L U2 R U R'",
        "L' U L U R U' R' U' R U R'"
      ],
      "FL": [
        "L U' L' U L' U' L U' L' U L"
      ],
      "BL": [
        "R' U R U L U' L' U' L U L'"
      ],
      "BR": [
        "R U R' U' R U' R' U R' U' R",
        "R U' R' U R' U' R U' R' U R"
      ]
    }
  },
  {
    "name": "AF2L 32",
    "group": "Both Pieces Trapped",
    "setup": "Fw' L Fw U2' L U L' U' R U' R'",
    "canonicalTarget": "BL",
    "algorithms": {
      "FR": [
        "L U' L' y L' U' L U' L' U L",
        "L U' L' y' R' U' R U' R' U R",
        "L U L' U' L U' L' b' R' b",
        "L U' L' F' L F' L' F2"
      ],
      "FL": [
        "R' U R U' L' U L d' L U L'",
        "R' U R y L U' L' U' L U L'",
        "R' U R y' R U' R' U' R U R'"
      ],
      "BL": [
        "R U R' U' R U' R' f' L' f",
        "R U' R' U f' U' L' U L' f",
        "R U R' F R U R' U' F' L U2 L'",
        "R U' R' y R' U' R U' R' U R"
      ],
      "BR": [
        "F U' R U' R' U R' U' R F'",
        "L' U L y' L U' L' U' L U L'",
        "L' U L U L' U L U f R f'"
      ]
    }
  },
  {
    "name": "AF2L 33",
    "group": "Both Pieces Trapped",
    "setup": "L' U L U R U R' U R U' R'",
    "canonicalTarget": "FL",
    "algorithms": {
      "FR": [
        "R' U R U R' U R2 U R'",
        "R' U R2 U R' U R U R'"
      ],
      "FL": [
        "R U' R' U' L' U' L U' L' U L",
        "R U R' U' R U' R' U' L' U' L",
        "R U' R' F' r' F' r2 U r'",
        "y' R' U R2 U R' U R U R'"
      ],
      "BL": [
        "L' U L2 U L' U L U L'",
        "L' U L U L' U L2 U L'"
      ],
      "BR": [
        "L U' L' U' R' U' R U' R' U R"
      ]
    }
  },
  {
    "name": "AF2L 34",
    "group": "Both Pieces Trapped",
    "setup": "F' R' U R U R' U' R F",
    "canonicalTarget": "BR",
    "algorithms": {
      "FR": [
        "L' U' L U y' R' U R U' R' U' R",
        "L' U L y' U2 R' U2 R U' R' U R",
        "L' U' L d R' U R U' R' U' R",
        "F U' R U' R' F' R U' R' U' R U R'"
      ],
      "FL": [
        "L U L' y U2 L U2 L' U' L U L'",
        "L U' L' U' L U L' U y L U' L'",
        "L U' L' U' L U L' F' L F L'"
      ],
      "BL": [
        "R' U' R y U R' U R U' R' U' R",
        "R' U R y U2 R' U2 R U' R' U R"
      ],
      "BR": [
        "F' R' U R U' R' U' R F",
        "R U' R' U' R U R' U f R' f'",
        "R U' R' U' R U R' r' U' R U M'",
        "R U' R2 f' U' f R"
      ]
    }
  },
  {
    "name": "AF2L 35",
    "group": "Both Pieces Trapped",
    "setup": "L U' L' U L U2' L' R U2' R'",
    "canonicalTarget": "BL",
    "algorithms": {
      "FR": [
        "L U' L' U' L U L' R U' R'",
        "L U L' U R U2 R' U' R U R'",
        "y' L' U L U R' U2 R U' R' U R"
      ],
      "FL": [
        "R' U R U L' U2 L U' L' U L",
        "R' U' R L' U L U' L' U' L",
        "y R U2 R' L U2 L' U' L U L'",
        "y R U' R' U' R U R' L U' L'"
      ],
      "BL": [
        "R U' R' U' R U R' L U' L'",
        "R U' R' U' R U M' B' r'",
        "R U R' U' R U2 R' U L U L'",
        "R U2 R' L U2 L' U' L U L'"
      ],
      "BR": [
        "L' U' L R' U R U' R' U' R",
        "L' U L U R' U2 R U' R' U R"
      ]
    }
  },
  {
    "name": "AF2L 36",
    "group": "Both Pieces Trapped",
    "setup": "F U' F' U F U2' F' R U' R'",
    "canonicalTarget": "FL",
    "algorithms": {
      "FR": [
        "R' U2 R y' R' U R U' R' U' R",
        "R' U R y' R' U2 R U' R' U R",
        "R' U R U' R' U2 L F' R2 U' R2 U F L' R",
        "R' U R2 U' R2 F R F' R U' R'"
      ],
      "FL": [
        "R' F R2 U' R' U' R U R' U2 F'",
        "R' F R F' U2 L' U L U' L' U' L",
        "R U' R' U' R U R' U' F U' F'",
        "R U' R' U' R U R' F U2 F'"
      ],
      "BL": [
        "L' U' L d' R' U R U' R' U' R",
        "L' U L y R' U2 R U' R' U R",
        "L' U L y' L' U2 L U' L' U L",
        "F U L U2 L' U' L U L' F'"
      ],
      "BR": [
        "L U' L' U' L U L' y' L U2 L'",
        "L U L' y' L U2 L' U' L U L'",
        "L U' L' R' F R U R' U' F' R"
      ]
    }
  },
  {
    "name": "AF2L 37",
    "group": "Both Pieces Trapped",
    "setup": "Fw R' Fw' R U R' U2' R U' R'",
    "canonicalTarget": "BR",
    "algorithms": {
      "FR": [
        "L' U' L y' R' U2 R U R' U' R",
        "L' U' L y L' U2 L U L' U' L",
        "L' U L U L' U' L y' R' U2 R",
        "F U2 R U' R' F' U R U R'"
      ],
      "FL": [
        "L U' L' y L U2 L' U L U' L'",
        "L U L' y U L U' L' U L U L'"
      ],
      "BL": [
        "R' U R U R' U' R y R' U2 R",
        "R' U' R y R' U2 R U R' U' R"
      ],
      "BR": [
        "R U R' U2 R U' R' f R f'",
        "F' U' R' U2 R U R' U' R F",
        "R U' R' y R U2 R' U R U' R'",
        "R U' R' U R U2 R' y R U' R'"
      ]
    }
  },
  {
    "name": "AF2L 38",
    "group": "Both Pieces Trapped",
    "setup": "L U' L' U' L U L' R U' R'",
    "canonicalTarget": "BL",
    "algorithms": {
      "FR": [
        "L U' L' U' R U2 R' U R U' R'",
        "L U L' R U' R' U R U R'"
      ],
      "FL": [
        "R' U' R U' L' U2 L U L' U' L",
        "R' U R U R' U' R L' U L"
      ],
      "BL": [
        "R U' R' U R U2 R' L U2 L'",
        "R U' R' U' L U2 L' U L U' L'",
        "R U R' L U' L' U L U L'",
        "R U' R' U R U2 R' U' L U' L'"
      ],
      "BR": [
        "L' U L U L' U' L R' U R",
        "F U2 R U' R' f R f' F'",
        "L' U2 L R' U2 R U R' U' R"
      ]
    }
  },
  {
    "name": "AF2L 39",
    "group": "Both Pieces Trapped",
    "setup": "F U' F' U' F U F' U R U' R'",
    "canonicalTarget": "FL",
    "algorithms": {
      "FR": [
        "R' U' R y' U2 R' U2 R U R' U' R",
        "R' U R L F' R' F R F L'",
        "R' U' R U d R' U2 R U R' U' R"
      ],
      "FL": [
        "R U R' d' L U' L' U L U L'",
        "R U R' U' y' R U' R' U R U R'",
        "R U R' L' U L U' L F' L' F L' U L",
        "R U' R' y' U2 R U2 R' U R U' R'"
      ],
      "BL": [
        "F L U' L' U L U L' F'",
        "L' U L l U' L' U L U l'",
        "L' U' L y U2 R' U2 R U R' U' R",
        "L' U' L y' U2 L' U2 L U L' U' L"
      ],
      "BR": [
        "L U' L' y' U2 L U2 L' U L U' L'",
        "L U L' y' U' L U' L' U L U L'",
        "f' L f U2 R' U' R U R' U2 R"
      ]
    }
  },
  {
    "name": "AF2L 40",
    "group": "Both Pieces Trapped",
    "setup": "R' U R2' U2' R' U' R U2' R'",
    "canonicalTarget": "BR",
    "algorithms": {
      "FR": [
        "F2 R' F2 D' R U' R' D R",
        "L' U' L R U' R' U R U' R' U2 R U' R'",
        "L' U' L R' U2 R2 U R2 U R",
        "L' U L U2 R U2 R' U2 R U' R'"
      ],
      "FL": [
        "L U' L2 U2 L U2 L' U L",
        "L U' L2 U2 L U L' U2 L"
      ],
      "BL": [
        "R' U R U2 L U2 L' U2 L U' L'"
      ],
      "BR": [
        "R U' R2 U2 R U R' U2 R",
        "R U' R2 U2 R U2 R' U R",
        "F R' F' R U' R U2 R2 U' R",
        "R' F R F' R U' R' U R U' R' U y R U' R'"
      ]
    }
  },
  {
    "name": "AF2L 41",
    "group": "Both Pieces Trapped",
    "setup": "Fw' L Fw U R U2' R' U' R U2' R'",
    "canonicalTarget": "BL",
    "algorithms": {
      "FR": [
        "L U L' R U2 R' y' U R' U' R",
        "L U L' R U2 R' U F' U' F"
      ],
      "FL": [
        "R' U R y' U R U2 R' U2 R U' R'",
        "R' U' R L' U2 L y U' L U L'",
        "R' U' R L' U2 L U' F U F'"
      ],
      "BL": [
        "R U' R' d R' U2 R L' U L",
        "F' U2 L' U2 L2 U L' F",
        "R U' R' U y L' U2 L R' U R",
        "R U' R' y U' R' U2 R U R' U2 R"
      ],
      "BR": [
        "F U2 R U2 R2 U' R F'",
        "L' U L U2 r U2 R2 U' R2 U' r'"
      ]
    }
  },
  {
    "name": "AF2L 42",
    "group": "Both Pieces Trapped",
    "setup": "L U L2' U L2' U2' L' U R U2' R'",
    "canonicalTarget": "FL",
    "algorithms": {
      "FR": [
        "R' U R2 U2 R' U R' F R F'",
        "R' U R2 U2 R' U2 R U' R'",
        "R' U' R U2 R' U2 R2 U R'"
      ],
      "FL": [
        "R U' R' U2 L' U2 L U2 L' U L",
        "y' R' U R2 U2 R' U2 R U' R'",
        "y' R' U R2 U2 R' U' R U2 R'",
        "R' F R F' R U' R' U R U' R' d' L U' L'"
      ],
      "BL": [
        "L' U L2 U2 L' U2 L U' L'",
        "L' U L2 U2 L' U' L U2 L'",
        "L' U' L F' U' L F' L' F L U L' F"
      ],
      "BR": [
        "L U L' R U2 R2 U' R2 U' R'"
      ]
    }
  },
  {
    "name": "AF2L 1a",
    "group": "Trapped Corner",
    "setup": "f R S' R' F' R",
    "canonicalTarget": "BR",
    "algorithms": {
      "FR": [
        "L' U' L y' R' U' R",
        "L' U' L F' U' F",
        "U L' U' F' U' F L",
        "F' L F L' R U' R'"
      ],
      "FL": [
        "y R' U' R y R' U' R",
        "f' L' f L' U' L",
        "y' L' U' L F' U' F",
        "y' L' U' L y L' U' L"
      ],
      "BL": [
        "R' U' R y R' U' R",
        "R' U' R f' L' f",
        "B' R B R' L U' L'"
      ],
      "BR": [
        "U2 R U' R' U' R' U' R",
        "U' R U R2 U' R U' R' U R",
        "R' F R F' y R U' R'",
        "F' U' F R' U' R"
      ]
    }
  },
  {
    "name": "AF2L 2a",
    "group": "Trapped Corner",
    "setup": "L U2' L' F R' F' R",
    "canonicalTarget": "BL",
    "algorithms": {
      "FR": [
        "L' B L B' R U2 R'",
        "y' L' U' L U' R' U' R",
        "y R' U' R U' L' U' L",
        "U2 L U' L' y' U2 R' U' R"
      ],
      "FL": [
        "R' U' R U' L' U' L"
      ],
      "BL": [
        "R' F R F' L U2 L'",
        "R' F R F' U' L U' L'",
        "U2 R U' R' U2 B' U' B",
        "F' U' F U' y2 F' U' F"
      ],
      "BR": [
        "L' U' L U' R' U' R"
      ]
    }
  },
  {
    "name": "AF2L 3a",
    "group": "Trapped Corner",
    "setup": "r U' r' F U' F R' F' R",
    "canonicalTarget": "FL",
    "algorithms": {
      "FR": [
        "B' R B R' U2 R U' R'",
        "R' U' R U2 F' U' F",
        "R' U' R y U2 L' U' L",
        "R' U' R y' U2 R' U' R"
      ],
      "FL": [
        "R' F R2 U' R' U F'",
        "R' F R F' d R' F R F'",
        "F' U' F U2 L' U' L",
        "U2 R U' R' U L' U' L"
      ],
      "BL": [
        "F' L F L' U2 L U' L'",
        "L' U' L y U2 R' U' R",
        "L' U' L y' U2 L' U' L",
        "L' U' L U2 f' L' f"
      ],
      "BR": [
        "f' L' f U2 R' U' R",
        "y R' U' R y' U2 R' U' R",
        "y' L' U' L y U2 R' U' R",
        "U2 L U' L' U R' U' R"
      ]
    }
  },
  {
    "name": "AF2L 4a",
    "group": "Trapped Corner",
    "setup": "R' U2' R2' U' R' U'",
    "canonicalTarget": "BR",
    "algorithms": {
      "FR": [
        "U L' U L y' U2 R' U R",
        "U L' U L y U2 L' U L",
        "U L' U L U' F R' F' R"
      ],
      "FL": [
        "U L U L2 U2 L",
        "U L U2 L2 U L"
      ],
      "BL": [
        "U R' U R y U R' U2 R",
        "U R' U R y U2 R' U R",
        "U R' U R y' U2 L' U L"
      ],
      "BR": [
        "U R U R2 U2 R",
        "U R U2 R2 U R",
        "U R U' R' S R2 S'"
      ]
    }
  },
  {
    "name": "AF2L 5a",
    "group": "Trapped Corner",
    "setup": "f' L' f R U' R' U'",
    "canonicalTarget": "BL",
    "algorithms": {
      "FR": [
        "y' U L' U L R' U2 R",
        "y U R' U R L' U2 L",
        "U L U L' F' U F",
        "U L U L' y' R' U R"
      ],
      "FL": [
        "U R' U R L' U2 L"
      ],
      "BL": [
        "U R U R' f' L f",
        "y U L' U L R' U2 R",
        "U l U' F2 U l'",
        "U R B' U2 B R'"
      ],
      "BR": [
        "U L' U L R' U2 R"
      ]
    }
  },
  {
    "name": "AF2L 6a",
    "group": "Trapped Corner",
    "setup": "L' U' L U R U' R' U'",
    "canonicalTarget": "FL",
    "algorithms": {
      "FR": [
        "U S R S'",
        "y U R L' U L R'",
        "y' U L R' U R L'"
      ],
      "FL": [
        "U R L' U L R'",
        "y U L' U L f' L f",
        "U R U R' U' L' U L",
        "U M F M'"
      ],
      "BL": [
        "U S' L S",
        "U L' U L f' L f",
        "U L' U L y R' U R",
        "y U L R' U R L'"
      ],
      "BR": [
        "U L R' U R L'",
        "U L R' U L' R"
      ]
    }
  },
  {
    "name": "AF2L 7a",
    "group": "Trapped Corner",
    "setup": "R' U' R U2' R U R' U2'",
    "canonicalTarget": "BR",
    "algorithms": {
      "FR": [
        "y' U2 R U' R' U2 R' U R",
        "y' U2 R U' R' U R' U2 R",
        "L F L' F L F' L'",
        "U2 L F' L' F y' U' R' U' R"
      ],
      "FL": [
        "U2 L U' L' U2 L' U L",
        "L U2 L' U L' U' L",
        "U2 L U' L' U L' U2 L"
      ],
      "BL": [
        "y U2 R U' R' U2 R' U R",
        "R B R' B R B' R'",
        "l U R' U R U' l'",
        "y' U2 L U' L' U2 L' U L"
      ],
      "BR": [
        "U2 R U' R' U2 R' U R",
        "R U2 R' U R' U' R",
        "U2 R U' R' U R' U2 R",
        "U2 R U R' U2 R' U' R"
      ]
    }
  },
  {
    "name": "AF2L 8a",
    "group": "Trapped Corner",
    "setup": "f' L' f U' R U R' U2'",
    "canonicalTarget": "BL",
    "algorithms": {
      "FR": [
        "U2 L U' L' y L' U2 L",
        "U2 L U' L' y' R' U2 R"
      ],
      "FL": [
        "U L' D L U' L' U' D' L",
        "y U2 R U' R' y R' U2 R",
        "U2 f R f' U L' U' L"
      ],
      "BL": [
        "U2 R U' R' d L' U L",
        "R U2 R' f' L' f",
        "R U2 R' y R' U' R",
        "U2 R U' R' y R' U2 R"
      ],
      "BR": [
        "U2 L F' L' F U2 R' U' R",
        "U R' D R U' R' U' D' R",
        "U2 F U2 R' U' R F'",
        "y U2 L U' L' y L' U2 L"
      ]
    }
  },
  {
    "name": "AF2L 9a",
    "group": "Trapped Corner",
    "setup": "L' U' L R U R' U2'",
    "canonicalTarget": "FL",
    "algorithms": {
      "FR": [
        "y U2 R U' R' L' U L",
        "y' U2 L U' L' R' U R"
      ],
      "FL": [
        "U2 R U' R' L' U L",
        "R U2 R' U' L' U' L"
      ],
      "BL": [
        "y U2 L U' L' R' U R",
        "y' U2 R U' R' L' U L"
      ],
      "BR": [
        "U2 L U' L' R' U R",
        "L U2 L' U' R' U' R"
      ]
    }
  },
  {
    "name": "AF2L 10a",
    "group": "Trapped Edge",
    "setup": "F' R' U R F U",
    "canonicalTarget": "BR",
    "algorithms": {
      "FR": [
        "y' U' F' R' U' R F",
        "U' F U' F' U R U' R'",
        "U L' U2 L y U2 L' U' L"
      ],
      "FL": [
        "U' F' D' L' D F"
      ],
      "BL": [
        "y U' F' R' U' R F"
      ],
      "BR": [
        "U' R U' R' U f R' f'",
        "U' R U' R' d L U' L'",
        "d' R' D' F' D R"
      ]
    }
  },
  {
    "name": "AF2L 11a",
    "group": "Trapped Edge",
    "setup": "L F' U' F U L' U2'",
    "canonicalTarget": "BL",
    "algorithms": {
      "FR": [
        "U' L U L' U' F' U' F",
        "U' L U L' y U' L' U' L",
        "U' L U L' y' U' R' U' R"
      ],
      "FL": [
        "U' f R f' U' L' U' L",
        "y U2 L U' F' U F L'",
        "y' U2 L F' U' F L'"
      ],
      "BL": [
        "U' R U R' y' U' L' U' L",
        "U' R U R' U' f' L' f",
        "U' R U R' d' R' U' R",
        "U' R U R' U' y2 F' U' F"
      ],
      "BR": [
        "U' F U F' U' R' U' R",
        "U2 L F' L' F R' U' R"
      ]
    }
  },
  {
    "name": "AF2L 12a",
    "group": "Trapped Edge",
    "setup": "F U2' F' R U R' U",
    "canonicalTarget": "FL",
    "algorithms": {
      "FR": [
        "U R' U2 R y' R' U' R",
        "U R' U2 R y L' U' L"
      ],
      "FL": [
        "U' R U' R' U2 F' r U r'",
        "U' R U' R' y L U2 L'",
        "U' F' U2 L' U' L2 F L'",
        "U' R U' R' y' U' R U' R'"
      ],
      "BL": [
        "U L' U2 L y' L' U' L",
        "U' L' U' L y' U' L' U' L",
        "U L' U2 L y R' U' R"
      ],
      "BR": [
        "U' L U' L' y' L U2 L'"
      ]
    }
  }
];
