/**
 * Generated by `npx vite-node scripts/fetchAlgs.ts`. Do not edit by hand.
 *
 * Algorithms from speedcubedb.com/a/3x3, the same source as the primary algorithm in
 * `lastLayerCases.ts` and `f2lCases.ts`. Every one of them has been run against a
 * cube and solves the case it is filed under; see `algBank.ts` for what that means
 * and `algBank.test.ts` for the same checks run over this file.
 */

/** Where these came from and when, so a stale bank can be spotted. */
export const ALG_BANK_SOURCE = {
  url: "https://www.speedcubedb.com/a/3x3",
  fetched: "2026-09-23",
  algorithms: 930,
} as const;

/** Keyed by OLL case number. */
export const OLL_ALG_BANK: Record<string, readonly string[]> = {
  "1": [
    "R U2 R2 F R F' U2 R' F R F'",
    "y R U' R2 D' r U' r' D R2 U R'",
    "f R U R' U' R f' U' r' U' R U M'",
    "L' U2 L2 F' L' F U2 L F' L' F"
  ],
  "2": [
    "y' R U' R2 D' r U r' D R2 U R'",
    "F R U R' U' S R U R' U' f'",
    "F R U R' U' F' f R U R' U' f'",
    "y r U r' U2 R U2 R' U2 r U' r'"
  ],
  "3": [
    "y' f R U R' U' f' U' F R U R' U' F'",
    "y R' F2 R2 U2 R' F R U2 R2 F2 R",
    "r' R2 U R' U r U2 r' U M'",
    "M R U R' U r U2 r' U M'"
  ],
  "4": [
    "y' R' F2 R2 U2 R' F' R U2 R2 F2 R",
    "y' f R U R' U' f' U F R U R' U' F'",
    "R' F R F' U' S R' U' R U R S'",
    "y F U R U' R' F' U' F R U R' U' F'"
  ],
  "5": [
    "r' U2 R U R' U r",
    "y2 l' U2 L U L' U l",
    "y2 R' F2 r U r' F R",
    "y2 R' F2 L F L' F R"
  ],
  "6": [
    "r U2 R' U' R U' r'",
    "F U' R2 D R' U' R D' R2 U F'",
    "y2 l U2 L' U' L U' l'",
    "L F2 l' U' l F' L'"
  ],
  "7": [
    "r U R' U R U2 r'",
    "S' R U R' U R U2 R' U S",
    "L' U2 L U2 L F' L' F",
    "y2 f R U R' U' f' y2 F R' F' r U R U' r'"
  ],
  "8": [
    "y2 r' U' R U' R' U2 r",
    "l' U' L U' L' U2 l",
    "R U2 R' U2 R' F R F'",
    "R' F' r U' r' F2 R"
  ],
  "9": [
    "y R U R' U' R' F R2 U R' U' F'",
    "R U2 R' U' S' R U' R' S",
    "y2 F' U' F r U' r' U r U r'",
    "y' L' U' L U' L F' L' F L' U2 L"
  ],
  "10": [
    "R U R' U R' F R F' R U2 R'",
    "y F U F' R' F R U' R' F' R",
    "y M' R' U2 R U R' U R U M",
    "y2 L' U' L U L F' L2 U' L U F"
  ],
  "11": [
    "r' R2 U R' U R U2 R' U M'",
    "y2 r U R' U R' F R F' R U2 r'",
    "S R U R' U R U2 R' U2 S'",
    "M R U R' U R U2 R' U M'"
  ],
  "12": [
    "y' M' R' U' R U' R' U2 R U' M",
    "F R U R' U' F' U F R U R' U' F'",
    "y' S R' U' R U' R' U2 R U2 S'",
    "y M L' U' L U' L' U2 L U' M'"
  ],
  "13": [
    "F U R U2 R' U' R U R' F'",
    "F U R U' R2 F' R U R U' R'",
    "r U' r' U' r U r' F' U F",
    "y2 f R U R2 U' R' U R U' f'"
  ],
  "14": [
    "R' F R U R' F' R F U' F'",
    "r U R' U' r' F R2 U R' U' F'",
    "l' U l U l' U' l F U' F'",
    "S R U R' U' R' F R2 U R' U' f'"
  ],
  "15": [
    "r' U' r R' U' R U r' U r",
    "y2 l' U' l L' U' L U l' U l",
    "r' U' M' U' R U r' U r",
    "y2 R' F' R L' U' L U R' F R"
  ],
  "16": [
    "r U r' R U R' U' r U' r'",
    "r U M U R' U' r U' r'",
    "y2 R' F R U R' U' F' R U' R' U2 R",
    "y2 l U l' L U L' U' l U' l'"
  ],
  "17": [
    "R U R' U R' F R F' U2 R' F R F'",
    "y2 F R' F' R U S' R U' R' S",
    "y2 F R' F' R2 r' U R U' R' U' M'",
    "y' F' r U r' U' S r' F r S'"
  ],
  "18": [
    "y R U2 R2 F R F' U2 M' U R U' r'",
    "r U R' U R U2 r2 U' R U' R' U2 r",
    "y F S' R U' R' S R U2 R' U' F'",
    "R D r' U' r D' R' U' R2 F R F' R"
  ],
  "19": [
    "y S' R U R' S U' R' F R F'",
    "M U R U R' U' M' R' F R F'",
    "R' U2 F R U R' U' F2 U2 F R",
    "r' R U R U R' U' r R2 F R F'"
  ],
  "20": [
    "r U R' U' M2 U R U' R' U' M'",
    "M' U2 M U2 M' U M U2 M' U2 M",
    "S' R U R' S U' M' U R U' r'",
    "S R' U' R U R U R U' R' S'"
  ],
  "21": [
    "R U R' U R U' R' U R U2 R'",
    "y R U2 R' U' R U R' U' R U' R'",
    "y F R U R' U' R U R' U' R U R' U' F'",
    "R' U' R U' R' U R U' R' U2 R"
  ],
  "22": [
    "R U2 R2 U' R2 U' R2 U2 R",
    "R' U2 R2 U R2 U R2 U2 R'",
    "f R U R' U' S' R U R' U' F'",
    "f R U R' U' f' F R U R' U' F'"
  ],
  "23": [
    "R2 D R' U2 R D' R' U2 R'",
    "y2 R2 D' R U2 R' D R U2 R",
    "R U R' U R U2 R2 U' R U' R' U2 R",
    "y R U R' U' R U' R' U2 R U' R' U2 R U R'"
  ],
  "24": [
    "r U R' U' r' F R F'",
    "y2 R' F' r U R U' r' F",
    "y R U R D R' U' R D' R2",
    "y' x' R U R' D R U' R' D' x"
  ],
  "25": [
    "R U2 R D R' U2 R D' R2",
    "y F' r U R' U' r' F R",
    "F R' F' r U R U' r'",
    "x R' U R D' R' U' R D x'"
  ],
  "26": [
    "y R U2 R' U' R U' R'",
    "R' U' R U' R' U2 R",
    "y2 L' U' L U' L' U2 L",
    "y2 L' U R U' L U R'"
  ],
  "27": [
    "R U R' U R U2 R'",
    "y' R' U2 R U R' U R",
    "y L' U2 L U L' U L",
    "y2 L U L' U L U2 L'"
  ],
  "28": [
    "r U R' U' M U R U' R'",
    "r U R' U' r' R U R U' R'",
    "R' F R S R' F' R S'",
    "y2 M' U M U2 M' U M"
  ],
  "29": [
    "r2 D' r U r' D r2 U' r' U' r",
    "y R U R' U' R U' R' F' U' F R U R'",
    "y S' R U R' U' R' F R F' U S",
    "M U R U R' U' R' F R F' M'"
  ],
  "30": [
    "y' r' D' r U' r' D r2 U' r' U r U r'",
    "y2 F U R U2 R' U' R U2 R' U' F'",
    "y2 F R' F R2 U' R' U' R U R' F2",
    "y S' R' U' R f R' U R U' F'"
  ],
  "31": [
    "R' U' F U R U' R' F' R",
    "y2 S' L' U' L U L F' L' f",
    "y S R U R' U' f' U' F",
    "y' F R' F' R U R U R' U' R U' R'"
  ],
  "32": [
    "S R U R' U' R' F R f'",
    "y2 L U F' U' L' U L F L'",
    "R U B' U' R' U R B R'",
    "y' R' F R F' U' r U' r' U r U r'"
  ],
  "33": [
    "R U R' U' R' F R F'",
    "y2 L' U' L U L F' L' F",
    "y2 r' F' r U r U' r' F",
    "R U R' F' U' F R U' R'"
  ],
  "34": [
    "y f R f' U' r' U' R U M'",
    "y2 R U R2 U' R' F R U R U' F'",
    "F R U R' U' R' F' r U R U' r'",
    "y2 R U R' U' B' R' F R F' B"
  ],
  "35": [
    "R U2 R2 F R F' R U2 R'",
    "f R U R' U' f' R U R' U R U2 R'",
    "R U2 R' d' R' F R U' R' F' R",
    "y L' U2 L2 F' L' F L' U2 L"
  ],
  "36": [
    "y R U R2 F' U' F U R2 U2 R'",
    "y2 L' U' L U' L' U L U L F' L' F",
    "y2 R U R' F' R U R' U' R' F R U' R' F R F'",
    "R U R' U' F' U2 F U R U R'"
  ],
  "37": [
    "F R' F' R U R U' R'",
    "F R U' R' U' R U R' F'",
    "y F' r U r' U' r' F r",
    "y2 r2 D' r U' r' D r U r"
  ],
  "38": [
    "R U R' U R U' R' U' R' F R F'",
    "y F R U' R' S U' R U R' f'",
    "r U R' U' r' F R U R U' R' F'",
    "y2 L U L' U L U' L' U' L' B L B'"
  ],
  "39": [
    "y' f' r U r' U' r' F r S",
    "y' R U R' F' U' F U R U2 R'",
    "y L F' L' U' L U F U' L'",
    "y' f' L F L' U' L' U L S"
  ],
  "40": [
    "y R' F R U R' U' F' U R",
    "y' f R' F' R U R U' R' S'",
    "R r D r' U r D' r' U' R'",
    "y' L' U' L F U F' U' L' U2 L"
  ],
  "41": [
    "y2 R U R' U R U2 R' F R U R' U' F'",
    "y2 F U R2 D R' U' R D' R2 F'",
    "y' S U' R' F' U' F U R S'",
    "M U' F' L' U' L U F M'"
  ],
  "42": [
    "R' U' R U' R' U2 R F R U R' U' F'",
    "y F S' R U R' U' F' U S",
    "y R' F R F' R' F R F' R U R' U' R U R'",
    "y R' U' F2 u' R U R' D R2 B"
  ],
  "43": [
    "y R' U' F' U F R",
    "y2 F' U' L' U L F",
    "f' L' U' L U f",
    "B' U' R' U R B"
  ],
  "44": [
    "f R U R' U' f'",
    "y2 F U R U' R' F'",
    "y R U B U' B' R'",
    "y' L U F U' F' L'"
  ],
  "45": [
    "F R U R' U' F'",
    "y R' F' U' F U R",
    "y2 f U R U' R' f'",
    "y2 F' L' U' L U F"
  ],
  "46": [
    "R' U' R' F R F' U R",
    "R' F' U' F R U' R' U2 R",
    "y F R U R' U' F' U' R U R' U R U2 R'",
    "l' U2 L2 F' L' F U L' U l"
  ],
  "47": [
    "y' F R' F' R U2 R U' R' U R U2 R'",
    "F' L' U' L U L' U' L U F",
    "R' U' R' F R F' R' F R F' U R",
    "y' R' F' U' F U F' U' F U R"
  ],
  "48": [
    "F R U R' U' R U R' U' F'",
    "y2 f U R U' R' U R U' R' f'",
    "R U2 R' U' R U R' U2 R' F R F'",
    "F R' F' U2 R U R' U R2 U2 R'"
  ],
  "49": [
    "y2 r U' r2 U r2 U r2 U' r",
    "l U' l2 U l2 U l2 U' l",
    "R B' R2 F R2 B R2 F' R",
    "y2 R' F R' F' R2 U2 B' R B R'"
  ],
  "50": [
    "r' U r2 U' r2 U' r2 U r'",
    "y2 R' F R2 B' R2 F' R2 B R'",
    "y' R U2 R' U' R U' R' F R U R' U' F'",
    "y2 l' U l2 U' l2 U' l2 U l'"
  ],
  "51": [
    "y2 F U R U' R' U R U' R' F'",
    "f R U R' U' R U R' U' f'",
    "y' R' U' R' F R F' R U' R' U2 R",
    "y r' F' U' F U F' U' F U r"
  ],
  "52": [
    "y2 R' F' U' F U' R U R' U R",
    "R U R' U R U' B U' B' R'",
    "R U R' U R d' R U' R' F'",
    "R U R' U R U' y R U' R' F'"
  ],
  "53": [
    "r' U' R U' R' U R U' R' U2 r",
    "y2 l' U' L U' L' U L U' L' U2 l",
    "y r' U2 R U R' U' R U R' U r",
    "y' l' U2 L U L' U' L U L' U l"
  ],
  "54": [
    "r U R' U R U' R' U R U2 r'",
    "y' r U2 R' U' R U R' U' R U' r'",
    "y' r U r' R U R' U' R U R' U' r U' r'",
    "y2 l U L' U L U' L' U L U2 l'"
  ],
  "55": [
    "y R' F U R U' R2 F' R2 U R' U' R",
    "y R' F R U R U' R2 F' R2 U' R' U R U R'",
    "R U2 R2 U' R U' R' U2 F R F'",
    "r U2 R2 F R F' U2 r' F R F'"
  ],
  "56": [
    "r U r' U R U' R' U R U' R' r U' r'",
    "r U r' U R U' R' M' U R U2 r'",
    "F R U R' U' R F' r U R' U' r'",
    "r' U' r U' R' U R U' R' U R r' U r"
  ],
  "57": [
    "R U R' U' M' U R U' r'",
    "y R U' R' S' R U R' S",
    "y R U R' S' R U' R' S",
    "R U R' U' R' r U R U' r'"
  ]
};

/** Keyed by PLL case letter. */
export const PLL_ALG_BANK: Record<string, readonly string[]> = {
  "Aa": [
    "x R' U R' D2 R U' R' D2 R2 x'",
    "l' U R' D2 R U' R' D2 R2 x'",
    "y x' R2 D2 R' U' R D2 R' U R' x"
  ],
  "Ab": [
    "x R2 D2 R U R' D2 R U' R x'",
    "y x' R U' R D2 R' U R D2 R2 x",
    "R' B' R U' R D R' U R D' R2 B R"
  ],
  "E": [
    "y x' R U' R' D R U R' D' R U R' D R U' R' D' x",
    "y R' U' R' D' R U' R' D R U R' D' R U R' D R2",
    "R2 U F' R' U R U' R' U R U' R' U R U' F U' R2"
  ],
  "F": [
    "y R' U' F' R U R' U' R' F R2 U' R' U' R U R' U R",
    "y R' F R f' R' F R2 U R' U' R' F' R2 U R' S",
    "R' U R U' R2 F' U' F U R F R' F' R2",
    "y R2 F R F' R' U' F' U F R2 U R' U' R"
  ],
  "Ga": [
    "R2 U R' U R' U' R U' R2 D U' R' U R D'",
    "R2 u R' U R' U' R u' R2 F' U F",
    "y R U R' F' R U R' U' R' F R U' R' F R2 U' R' U' R U R' F'",
    "D' R2 U R' U R' U' R U' R2 U' D R' U R"
  ],
  "Gb": [
    "D R' U' R U D' R2 U R' U R U' R U' R2",
    "R' U' R U D' R2 U R' U R U' R U' R2 D",
    "y F' U' F R2 u R' U R U' R u' R2",
    "R' d' F R2 u R' U R U' R u' R2"
  ],
  "Gc": [
    "R2 U' R U' R U R' U R2 D' U R U' R' D",
    "y2 R2 F2 R U2 R U2 R' F R U R' U' R' F R2",
    "D R2 U' R U' R U R' U R2 D' U R U' R'",
    "R2 u' R U' R U R' u R2 f R' f'"
  ],
  "Gd": [
    "R U R' U' D R2 U' R U' R' U R' U R2 D'",
    "D' R U R' U' D R2 U' R U' R' U R' U R2",
    "R U R' y' R2 u' R U' R' U R' u R2",
    "y R2 F' R U R U' R' F' R U2 R' U2 R' F2 R2"
  ],
  "H": [
    "M2 U M2 U2 M2 U M2",
    "M2 U' M2 U2 M2 U' M2",
    "R2 S2 R2 U' R2 S2 R2",
    "M2 U2 M2 U M2 U2 M2"
  ],
  "Ja": [
    "y2 x R2 F R F' R U2 r' U r U2 x'",
    "y R' U L' U2 R U' R' U2 R L",
    "L' U' L F L' U' L U L F' L2 U L",
    "R U' L' U R' U2 L U' L' U2 L"
  ],
  "Jb": [
    "R U R' F' R U R' U' R' F R2 U' R'",
    "R U2 R' U' R U2 L' U R' U' L",
    "r' F R F' r U2 R' U R U2 R'",
    "L' U R U' L U2 R' U R U2 R'"
  ],
  "Na": [
    "R U R' U R U R' F' R U R' U' R' F R2 U' R' U2 R U' R'",
    "F' R U R' U' R' F R2 F U' R' U' R U F' R'",
    "R F U' R' U R U F' R2 F' R U R U' R' F",
    "r' D r U2 r' D r U2 r' D r U2 r' D r U2 r' D r"
  ],
  "Nb": [
    "R' U R U' R' F' U' F R U R' F R' F' R U' R",
    "r' D' F r U' r' F' D r2 U r' U' r' F r F'",
    "R' U L' U2 R U' L R' U L' U2 R U' L",
    "R' U R U' R' F' U' F R U R' U' R U' f R f'"
  ],
  "Ra": [
    "y R U' R' U' R U R D R' U' R D' R' U2 R'",
    "y R U R' F' R U2 R' U2 R' F R U R U2 R'",
    "L U2 L' U2 L F' L' U' L U L F L2",
    "y R U' R' U' R U R' U R' D' R U' R' D R2 U R'"
  ],
  "Rb": [
    "R' U2 R U2 R' F R U R' U' R' F' R2",
    "y R2 F R U R U' R' F' R U2 R' U2 R",
    "R' U2 R' D' R U' R' D R U R U' R' U' R",
    "y R' U R U R' U' R' D' R U R' D R U2 R"
  ],
  "T": [
    "R U R' U' R' F R2 U' R' U' R U R' F'",
    "R U R' U' R' F R2 U' R' U F' L' U L",
    "R2 u R2 u' R2 F2 u' F2 u F2"
  ],
  "Ua": [
    "y2 M2 U M U2 M' U M2",
    "R U R' U R' U' R2 U' R' U R' U R",
    "y R2 U' S' U2 S U' R2",
    "y2 R U' R U R U R U' R' U' R2"
  ],
  "Ub": [
    "y2 M2 U' M U2 M' U' M2",
    "R' U R' U' R' U' R' U R U R2",
    "R2' U R U R' U' R3 U' R' U R'",
    "y2 R2 U R U R' U' R' U' R' U R'"
  ],
  "V": [
    "R' U R' U' R D' R' D R' U D' R2 U' R2 D R2",
    "R' U R U' R' f' U' R U2 R' U' R U' R' f R",
    "R' U R' U' y R' F' R2 U' R' U R' F R F",
    "y R U' R U R' D R D' R U' D R2 U R2 D' R2"
  ],
  "Y": [
    "F R U' R' U' R U R' F' R U R' U' R' F R F'",
    "F R' F R2 U' R' U' R U R' F' R U R' U' F'",
    "R2 U' R2 U' R2 U F U F' R2 F U' F'",
    "F R' F' R U R U' R2 U' R U R f' U' f"
  ],
  "Z": [
    "M' U' M2 U' M2 U' M' U2 M2",
    "M2 U M2 U M' U2 M2 U2 M'",
    "y M2 U' M2 U' M' U2 M2 U2 M'",
    "y M' U M2 U M2 U M' U2 M2"
  ]
};

/** Keyed by case name, then by the slot the pair goes into. */
export const F2L_ALG_BANK: Record<
  string,
  Partial<Record<string, readonly string[]>>
> = {
  "F2L 1": {
    "FR": [
      "U R U' R'",
      "R' F R F'",
      "y' r' U' R U M'",
      "y U F' L F L2 U L"
    ],
    "FL": [
      "F' r U r'",
      "d R U' R'",
      "F' L F L'",
      "y' U R U' R'"
    ],
    "BL": [
      "U L U' L'",
      "L' f U f'",
      "U2 L U2 L'",
      "U' r U B' U' B r'"
    ],
    "BR": [
      "U f R' f'",
      "r' U' R U M'",
      "d L U' L'",
      "y' U L U' L'"
    ]
  },
  "F2L 2": {
    "FR": [
      "F R' F' R",
      "y' U' R' U R",
      "U' F' U F",
      "y U' L' U L"
    ],
    "FL": [
      "U' L' U L",
      "L F' L' F",
      "r U' r' F",
      "U r' U' F U F' r"
    ],
    "BL": [
      "l U L' U' M'",
      "U' f' L f",
      "d' R' U R",
      "y' U' L' U L"
    ],
    "BR": [
      "U' R' U R",
      "R f' U' f",
      "U2 R' U2 R",
      "U R' F' U F U' R"
    ]
  },
  "F2L 3": {
    "FR": [
      "F' U' F",
      "y' R' U' R",
      "y L' U' L",
      "S U R U' R' S'"
    ],
    "FL": [
      "L' U' L",
      "U2 R' F R U R' F' R",
      "y' S U R U' R' S'",
      "U S' F U' F' U S"
    ],
    "BL": [
      "y R' U' R",
      "f' L' f",
      "f' r' U z",
      "U' R U B' U' B R'"
    ],
    "BR": [
      "R' U' R",
      "U2 r' R' F R F' r",
      "U S f R' f' U S'",
      "U f2 F' R' f' U S'"
    ]
  },
  "F2L 4": {
    "FR": [
      "R U R'",
      "y' f R f'",
      "y F U F'",
      "y2 L U L'"
    ],
    "FL": [
      "F U F'",
      "y L U L'",
      "S' L F' L' f",
      "U' M L' U L U' M'"
    ],
    "BL": [
      "L U L'",
      "r B r'",
      "U f R U R' U2 f' r x'",
      "y2 R U R'"
    ],
    "BR": [
      "f R f'",
      "y' L U L'",
      "y R U R'",
      "U' r R2 U R U' M"
    ]
  },
  "F2L 5": {
    "FR": [
      "U' R U R' U2 R U' R'",
      "F2 L' U' L U F2",
      "U' R U R' U' R U2 R'",
      "U' R U R' U R' F R F'"
    ],
    "FL": [
      "U R' F r U' r' F' R",
      "U2 F R U R' U2 F'",
      "U l' U L U' L' U' l",
      "y' U' R U R' U2 R U' R'"
    ],
    "BL": [
      "U' L U L' U2 L U' L'",
      "U' L U L' U' L U2 L'",
      "y2 U' R U R' U2 R U' R'",
      "U y' l' U L U' L' U' l"
    ],
    "BR": [
      "U' R' F R U R' U' F' R",
      "R2 F' U' F U R2",
      "U r' U R U' R' U' r",
      "d' R U R' U2 R U' R'"
    ]
  },
  "F2L 6": {
    "FR": [
      "U' r U' R' U R U r'",
      "y' U R' U' R U2 R' U R",
      "d R' U' R U2 R' U R",
      "y U L' U' L U2 L' U L"
    ],
    "FL": [
      "U L' U' L U2 L' U L",
      "F2 R U R' U' F2",
      "R' F2 R U R' U' F2 U R",
      "U L' U' L U L' U2 L"
    ],
    "BL": [
      "U r U' r' U' L U F L'",
      "y U R' U' R U R' U2 R",
      "U' l U' L' U L U l'",
      "U L F' L' U' L U F L'"
    ],
    "BR": [
      "U R' U' R U2 R' U R",
      "U2 R' F' U' F U2 R",
      "y2 U L' U' L U2 L' U L",
      "U' y r U' R' U R U r'"
    ]
  },
  "F2L 7": {
    "FR": [
      "U' R U2 R' U' R U2 R'",
      "M' U' M U2 r U' r'",
      "U' R U2 R' U2 R U' R'",
      "U' R U2 R' U R' F R F'"
    ],
    "FL": [
      "F U R U2 R' U F'",
      "d' L U2 L' U2 L U' L'",
      "U' F U2 R U' R' U F'",
      "l U2 L2 U' L2 U' l'"
    ],
    "BL": [
      "U' L U2 L' U2 L U' L'",
      "U' L U2 L' U' L U2 L'",
      "M U' M' U2 l U' l'"
    ],
    "BR": [
      "r U2 R2 U' R2 U' r'",
      "F R U R2 U' R F'",
      "y' U' L U2 L' U2 L U' L'",
      "y U' R U2 R' U2 R U' R'"
    ]
  },
  "F2L 8": {
    "FR": [
      "r' U2 R2 U R2 U r",
      "d R' U2 R U R' U2 R",
      "y' U R' U2 R U2 R' U R",
      "y U L' U2 L U2 L' U L"
    ],
    "FL": [
      "U L' U2 L U L' U2 L",
      "U r' F2 r U2 r' F r",
      "U' R' U2 R U R' U R U2 L' U L",
      "U L' U2 L U' L F' L' F"
    ],
    "BL": [
      "l' U2 L2 U L2 U l",
      "y U R' U2 R U R' U2 R",
      "d L' U2 L U2 L' U L",
      "f' L' U' L2 U L' f"
    ],
    "BR": [
      "U R' U2 R U R' U2 R",
      "U R' U2 R U2 R' U R"
    ]
  },
  "F2L 9": {
    "FR": [
      "U' R U' R' U F' U' F",
      "F R U R' U' F' R U' R'",
      "U' R U' R' d R' U' R",
      "d R' U' R U' R' U' R"
    ],
    "FL": [
      "U L' U' L U' L' U' L",
      "F2 U R U' R' F2",
      "U' F U' F' U L' U' L",
      "L' U L U' L' U' L U2 L' U L"
    ],
    "BL": [
      "y U R' U' R U' R' U' R",
      "U' L U' L' U f' L' f",
      "d L' U' L U' L' U' L",
      "y U2 R' U R U R' U' R"
    ],
    "BR": [
      "U R' U' R U' R' U' R",
      "R' U R U' R' U' R U2 R' U R",
      "U2 R' U R U R' U' R",
      "U2 r U R' U R' U' R2 U' r'"
    ]
  },
  "F2L 10": {
    "FR": [
      "U' R U R' U R U R'",
      "U2 R U' R' U' R U R'",
      "d R' U R d' R U R'",
      "y' U R' U R U' f R f'"
    ],
    "FL": [
      "U L' U L U' F U F'",
      "F U' R U R' U2 F'",
      "d' L U L' U L U L'",
      "y' U' R U R' U R U R'"
    ],
    "BL": [
      "U' L U L' U L U L'",
      "U2 L U' L' U' L U L'",
      "L U' L' U L U L' U2 L U' L'",
      "y2 U' R U R' U R U R'"
    ],
    "BR": [
      "U R' U R U' f R f'",
      "R2 U' F' U F R2",
      "y U' R U R' U R U R'",
      "d' R U R' U R U R'"
    ]
  },
  "F2L 11": {
    "FR": [
      "U' R U2 R' U F' U' F",
      "y' R U2 R2 U' R2 U' R'",
      "U' R U2 R' d R' U' R",
      "F' U L' U2 L U2 F"
    ],
    "FL": [
      "L' U L U' L' U L U2 L' U L",
      "L U2 L2 U' L2 U' L'",
      "F U R U' R' U R U' R' U F'",
      "U' F U2 F' U r' F' r"
    ],
    "BL": [
      "U' L U2 L' U f' L' f",
      "U' L U2 L' d L' U' L",
      "L U2 L' U' l U' l' U2 l U l'",
      "y R U2 R2 U' R2 U' R'"
    ],
    "BR": [
      "R U2 R2 U' R2 U' R'",
      "R' U R U' R' U R U2 R' U R",
      "R' U R U' R' U R U R' U2 R",
      "d' R U2 R' U F' U' F"
    ]
  },
  "F2L 12": {
    "FR": [
      "R U' R' U R U' R' U2 R U' R'",
      "R' U2 R2 U R2 U R",
      "U F' U2 F U' R U R'",
      "U R U' R' U' R U R' U' R U R'"
    ],
    "FL": [
      "U L' U2 L U' F U F'",
      "U L' U2 L d' L U L'",
      "L' U2 L U l' U l U2 l' U' l",
      "y' R' U2 R2 U R2 U R"
    ],
    "BL": [
      "L' U2 L2 U L2 U L",
      "d L' U2 L U' F U F'",
      "U2 R' U2 R U2 L U L' U2 R' U R",
      "L U' L' U L U' L' U2 L U' L'"
    ],
    "BR": [
      "U R' U2 R U' f R f'",
      "f R' U R2 U' R2 f'",
      "U R' U2 R M U2 R' U R U M'",
      "U R' U2 R d' R U R'"
    ]
  },
  "F2L 13": {
    "FR": [
      "y' U R' U R U' R' U' R",
      "M' U' R U R' U2 R U' r'",
      "R U' R' U R' F R F' R U' R'",
      "d R' U R U' R' U' R"
    ],
    "FL": [
      "U L' U L U' L' U' L",
      "y' R U' R' U2 R U' R' U F' U F",
      "U L' U L U' L' U L U L' U L",
      "U L F' L2 U' L U L F L'"
    ],
    "BL": [
      "d L' U L U' L' U' L",
      "y U R' U R U' R' U' R",
      "U f' L f U' f' L' f",
      "U L U' L F' L2 U' L U F U L'"
    ],
    "BR": [
      "U R' U R U' R' U' R",
      "U R' U R U' R' U R U R' U R"
    ]
  },
  "F2L 14": {
    "FR": [
      "U' R U' R' U R U R'",
      "R U2 R' U2 R U R' U2 R U' R'",
      "U' R2 D R' U R D' R2",
      "U2 R2 U R' U R U2 R2"
    ],
    "FL": [
      "d' L U' L' U L U L'",
      "y U' L U' L' U L U L'",
      "y' U' R U' R' U R U R'",
      "M' U L' U' L U2 L' U l"
    ],
    "BL": [
      "U' L U' L' U L U L'",
      "U' L U' L' U L U' L' U' L U' L'"
    ],
    "BR": [
      "y U' R U' R' U R U R'",
      "d' R U' R' U R U R'",
      "U' f R' f' U f R f'",
      "y' U' L U' L' U L U L'"
    ]
  },
  "F2L 15": {
    "FR": [
      "M U r U' r' U' M'",
      "R U R' U2 R U' R' U R U' R'",
      "R' D' R U' R' D R U R U' R'",
      "F' U F U2 R U R'"
    ],
    "FL": [
      "F U2 R U R' U F'",
      "L' U L U2 F U F'",
      "L' U L U2 y L U L'",
      "U L' l U' l' U l U l' U L"
    ],
    "BL": [
      "L U L' U2 L U' L' U L U' L'",
      "M' U l U' l' U' M",
      "f' L f U2 L U L'",
      "L U2 L' U L U L' U L U' L'"
    ],
    "BR": [
      "R' U R U2 f R f'",
      "R2 F R F' R U R' U2 R",
      "R' U R U' d' R U R'",
      "R2 F R F' R U2 R' U R"
    ]
  },
  "F2L 16": {
    "FR": [
      "R U' R' U2 F' U' F",
      "R U' R' U2 y' R' U' R",
      "U M' U R U' r' U' R U R'",
      "U F U R U' R' F' R U R'"
    ],
    "FL": [
      "F U' R U' R' U2 F'",
      "L' U' L U2 L' U L U' L' U L",
      "L' U2 L U' L' U' L U' L' U L",
      "M U' l' U l U M'"
    ],
    "BL": [
      "L U' L' U2 f' L' f",
      "L2 F' L' F L' U2 L U' L'",
      "L U' L' y U2 R' U' R",
      "L U' L' U' d' R' U' R"
    ],
    "BR": [
      "R' U' R U2 R' U R U' R' U R",
      "M' U' r' U r U M",
      "U2 R' U' R U R D R' U' R D' R'",
      "F R' F' R U2 R' U' R2 U' R'"
    ]
  },
  "F2L 17": {
    "FR": [
      "R U2 R' U' R U R'",
      "y2 L U2 L' U' L U L'",
      "R U R' U' R U2 R' U2 R U R'",
      "y L F' L' F L' U L U' L' U L"
    ],
    "FL": [
      "L F' L' F L' U L U' L' U L",
      "y L U2 L' U' L U L'",
      "L' U2 L U2 l' U L U' L' U' l",
      "y' R U2 R' U' R U R'"
    ],
    "BL": [
      "L U2 L' U' L U L'",
      "L U L' U' L U2 L' U2 L U L'"
    ],
    "BR": [
      "R' U2 F R U R' U' F' R",
      "y' L U2 L' U' L U L'",
      "y R U2 R' U' R U R'",
      "l U' R' U l' U R U' R' U R"
    ]
  },
  "F2L 18": {
    "FR": [
      "y' R' U2 R U R' U' R",
      "y L' U2 L U L' U' L",
      "F' U2 F U F' U' F",
      "R' F R F' R U' R' U R U' R'"
    ],
    "FL": [
      "L' U2 L U L' U' L"
    ],
    "BL": [
      "y R' U2 R U R' U' R",
      "U F U R U' R' F' L U L'",
      "L U2 F' L' U' L U F L'",
      "L U2 L' U2 l U' L' U L U l'"
    ],
    "BR": [
      "R' U2 R U R' U' R"
    ]
  },
  "F2L 19": {
    "FR": [
      "U R U2 R' U R U' R'",
      "U R U2 R2 F R F'",
      "d f R2 f' U f R' f'",
      "R U' R' U R U' R' U R U R'"
    ],
    "FL": [
      "U L' U L2 F' L' F L' U L",
      "d R U2 R' U R U' R'",
      "y' U R U2 R' U R U' R'",
      "y U L U2 L' U L U' L'"
    ],
    "BL": [
      "U L U2 L' U L U' L'",
      "L U' L' U L U' L' U L U L'"
    ],
    "BR": [
      "y U R U2 R' U R U' R'",
      "U R' F' U2 F R U R' U' R",
      "d L U2 L' U L U' L'",
      "U2 f R2 U R2 U' R f'"
    ]
  },
  "F2L 20": {
    "FR": [
      "y' U' R' U2 R U' R' U R",
      "U' R U' R2 F R F' R U' R'",
      "y U' L' U2 L U' L' U L",
      "U' F' U2 F U' F' U F"
    ],
    "FL": [
      "U' L' U2 L U' L' U L",
      "L' U L U' L' U L U' L' U' L",
      "U' L' U2 L2 F' L' F"
    ],
    "BL": [
      "y U' R' U2 R U' R' U R",
      "U' L F U2 F' L' U' L U L'",
      "d' R' U2 R U' R' U R",
      "U' L U L' U l U' l' U2 l U l'"
    ],
    "BR": [
      "U' R' U2 R U' R' U R",
      "R' U R U' R' U R U' R' U' R"
    ]
  },
  "F2L 21": {
    "FR": [
      "U2 R U R' U R U' R'",
      "R U' R' U2 R U R'",
      "R B U2 B' R'",
      "y' f R' f' U2 f R f'"
    ],
    "FL": [
      "l' U l U2 l' U' l",
      "F R U2 R' F'",
      "y U2 L U L' U L U' L'",
      "y L U' L' U2 L U L'"
    ],
    "BL": [
      "L U' L' U2 L U L'",
      "U2 L U L' U L U' L'",
      "l U' L' U2 L U l'",
      "L F U2 F' L'"
    ],
    "BR": [
      "r' U r U2 r' U' r",
      "y' U2 L U L' U L U' L'",
      "U2 R' U' R S R f' U' F",
      "U f U R U' R f'"
    ]
  },
  "F2L 22": {
    "FR": [
      "r U' r' U2 r U r'",
      "F' L' U2 L F",
      "y' U2 R' U' R U' R' U R",
      "y U2 L' U' L U' L' U L"
    ],
    "FL": [
      "L' U L U2 L' U' L",
      "U2 L' U' L U' L' U L",
      "r' U' F2 U r",
      "U' L' U L U2 L' U L U' L' U L"
    ],
    "BL": [
      "l U' l' U2 l U l'",
      "f' U' L2 U f",
      "y R' U R U2 R' U' R",
      "y U2 R' U' R U' R' U R"
    ],
    "BR": [
      "R' U R U2 R' U' R",
      "U2 R' U' R U' R' U R",
      "R' F' U2 F R",
      "U' R' U R U2 R' U R U' R' U R"
    ]
  },
  "F2L 23": {
    "FR": [
      "U R U' R' U' R U' R' U R U' R'",
      "R U R' U2 R U R' U' R U R'",
      "U2 R2 U2 R' U' R U' R2",
      "R U' R2 D' R U2 R' D R"
    ],
    "FL": [
      "F' U' L' U L F L' U L",
      "U L' U' L2 F' L' F L' U L",
      "F U' R U R' U R U2 R' F'",
      "U' F R U' R' F' L' U' L"
    ],
    "BL": [
      "U L U' L' U' L U' L' U L U' L'",
      "L U L' U2 L U L' U' L U L'",
      "L' U' L U' L' U2 L2 U2 L'",
      "U2 L2 U2 L' U' L U' L2"
    ],
    "BR": [
      "U R' F R' F' R2 U' R' U R",
      "U2 l' U' L U' L' U2 B' l",
      "R' F' U' F U2 R U' R' U' R",
      "U R' U' F' U F R U' R' U R"
    ]
  },
  "F2L 24": {
    "FR": [
      "F U R U' R' F' R U' R'",
      "U' R U R2 F R F' R U' R'",
      "y' R' U' R U2 R' U' R U R' U' R",
      "U F' L' U L F R U R'"
    ],
    "FL": [
      "U' L' U L U L' U L U' L' U L",
      "U' F' r U r' U' L' U' L",
      "L' U L U L' U' L U2 L' U' L",
      "F U' R U2 R' U R U2 R' F'"
    ],
    "BL": [
      "U2 r U R' U R U2 B r'",
      "U' L F' L F L2 U L U' L'",
      "U2 F U R U' R' F' U2 L U' L'",
      "y U' R' U R U R' U R U' R' U R"
    ],
    "BR": [
      "R' U' R U2 R' U' R U R' U' R",
      "U2 R2 U2 R U R' U R2",
      "R U R' U R U2 R2 U2 R",
      "U' R' U R U R' U R U' R' U R"
    ]
  },
  "F2L 25": {
    "FR": [
      "U' R' F R F' R U R'",
      "R' F' R U R U' R' F",
      "U' F' U F U R U' R'",
      "l' U' l U l F' l' F"
    ],
    "FL": [
      "U' L' U L F' r U r'",
      "U' L' U L d R U' R'",
      "U' L' U L F' L F L'",
      "U' L' U L y U L U' L'"
    ],
    "BL": [
      "R D' R' U' R D R' L U L'",
      "L U' L' U' L U' L' U L U L'",
      "U' f' L' f U L U L'",
      "L' U' L' U' L' U L U L"
    ],
    "BR": [
      "U' R' U M U' R U M'",
      "R' S' R U' R' S R",
      "U' R' U R r' U' R U M'",
      "d' R' F R F' R U R'"
    ]
  },
  "F2L 26": {
    "FR": [
      "U R U' R' F R' F' R",
      "R S' R' U R S R'",
      "U R U R' U' y L' U' L",
      "U R U' R' U' F' U F"
    ],
    "FL": [
      "r U r' U' r' F r F'",
      "U L F' L' F L' U' L",
      "U F L' U' L U L F' L'",
      "U F r' F' r U r U' r'"
    ],
    "BL": [
      "L S L' U L S' L'",
      "F R2 u R u' R2 F'",
      "U' R u R' U R U' u' R'",
      "R E' R' U R E R'"
    ],
    "BR": [
      "U f R f' U' R' U' R",
      "R' U R U R' U R U' R' U' R",
      "R U R U R U' R' U' R'",
      "U' R S2 R' U' R S2 R'"
    ]
  },
  "F2L 27": {
    "FR": [
      "R U' R' U R U' R'",
      "F' U' F U2 R U' R'",
      "y' f R' f' U f R' f'",
      "y' f R' f' r' U' R U M'"
    ],
    "FL": [
      "L' U' L U F' r U r'",
      "L' U' L U F' L F L'",
      "y' R U' R' U R U' R'",
      "U' F R U2 R' U F'"
    ],
    "BL": [
      "L U' L' U L U' L'"
    ],
    "BR": [
      "R' U2 R' F R F' R",
      "R' U' R U r' U' R U M'",
      "y R U' R' U R U' R'",
      "R' U' R U f' U f R'"
    ]
  },
  "F2L 28": {
    "FR": [
      "R U R' U' F R' F' R",
      "y L' U L U' L' U L",
      "F' U F U' F' U F",
      "y' R' U R U' R' U R"
    ],
    "FL": [
      "L' U L U' L' U L",
      "L' U L2 F' L' F"
    ],
    "BL": [
      "L U2 L F' L' F L'",
      "y R' U R U' R' U R",
      "L U L' U' l U L' U' M'",
      "L U2 L' U f' L f"
    ],
    "BR": [
      "R' U R U' R' U R"
    ]
  },
  "F2L 29": {
    "FR": [
      "R' F R F' U R U' R'",
      "y L' U' L U L' U' L",
      "y' R' U' R U R' U' R",
      "R' F R F' R' F R F'"
    ],
    "FL": [
      "L' U' L U L' U' L",
      "U L' U2 L U2 L' U' L",
      "U F' L F L2 U' L",
      "F' L F L' F' L F L'"
    ],
    "BL": [
      "y R' U' R U R' U' R",
      "U2 L U' L' f' L' f",
      "f' L' f U f' L' f",
      "x' U' F' U F U' F' U x"
    ],
    "BR": [
      "R' U' R U R' U' R",
      "U R' U2 R U2 R' U' R",
      "U f' U f R2 U' R"
    ]
  },
  "F2L 30": {
    "FR": [
      "R U R' U' R U R'",
      "U' R U2 R' U2 R U R'",
      "U' F R' F' R2 U R'",
      "U2 F' U F R U R'"
    ],
    "FL": [
      "L F' L' F U' L' U L",
      "y' R U R' U' R U R'",
      "U' F U' R U2 R' F'",
      "y L U L' U' L U L'"
    ],
    "BL": [
      "L U L' U' L U L'",
      "U' L U2 L' U2 L U L'"
    ],
    "BR": [
      "y' L U L' U' L U L'",
      "f R f' U' f R f'",
      "U2 R' U R f R f'",
      "y R U R' U' R U R'"
    ]
  },
  "F2L 31": {
    "FR": [
      "U' R' F R F' R U' R'",
      "R U' R' U y' R' U R",
      "F' U F R U2 R'",
      "R U' R' U y L' U L"
    ],
    "FL": [
      "U L F' L' F L' U L",
      "L' U L U' y L U' L'",
      "L' U L F U2 F'",
      "U' F' L F L' F U' F'"
    ],
    "BL": [
      "L U' L F' L' F L'",
      "f' L f U' L U' L'",
      "B' U B L U2 L'",
      "L U2 L' U' l U L' U' M'"
    ],
    "BR": [
      "R' U R' F R F' R",
      "R' U R f R2 f'",
      "R' U R y R U2 R'",
      "f R' f' U R' U R"
    ]
  },
  "F2L 32": {
    "FR": [
      "U R U' R' U R U' R' U R U' R'",
      "R U R' U' R U R' U' R U R'",
      "R2 U R2 U R2 U2 R2",
      "U' F R' F' R U' R U R'"
    ],
    "FL": [
      "U' L' U L U' L' U L U' L' U L",
      "U L' U L U' L' U2 L U L' U' L",
      "U2 F U' R U R' U F'",
      "L' U' L U L' U' L U L' U' L"
    ],
    "BL": [
      "L U L' U' L U L' U' L U L'",
      "U L U' L' U L U' L' U L U' L'",
      "L2 U L2 U L2 U2 L2",
      "U' L U' L' U L U2 L' U' L U L'"
    ],
    "BR": [
      "U' R' U R U' R' U R U' R' U R",
      "R' U' R U R' U' R U R' U' R",
      "U2 f R' U R U' R f'",
      "R2 U' R2 U' R2 U2 R2"
    ]
  },
  "F2L 33": {
    "FR": [
      "U' R U' R' U2 R U' R'",
      "y R' D R U' R' D' R",
      "R U R' U' R U' R' U R U' R'",
      "U' R U' R' U' R U2 R'"
    ],
    "FL": [
      "R' D R U' R' D' R",
      "U L' U2 L U' L' U' L",
      "U' L D L' U L D' L'",
      "U' L' U' L U2 L' U' L"
    ],
    "BL": [
      "U' L U' L' U2 L U' L'",
      "U' L U' L' U' L U2 L'",
      "D' R D R' U R D' R' D"
    ],
    "BR": [
      "U' R D R' U R D' R'",
      "U R' U2 R U' R' U' R",
      "U' R' U' R U2 R' U' R",
      "U R D R' U' R D' R'"
    ]
  },
  "F2L 34": {
    "FR": [
      "U R U R' U2 R U R'",
      "U' R U2 R' U R U R'",
      "U R' D' R U' R' D R",
      "y U L' U L U2 L' U L"
    ],
    "FL": [
      "U L' U L U2 L' U L",
      "U L' U L U L' U2 L",
      "L' U' L U L' U L U' L' U L"
    ],
    "BL": [
      "U L U L' U2 L U L'",
      "U L' D' L U' L' D L",
      "U' L U2 L' U L U L'",
      "U2 R D' R' U' R D R'"
    ],
    "BR": [
      "U R' U R U R' U2 R",
      "U f R2 U R2 U' f'",
      "U R2 F R F' R U' R' U R",
      "U R' U R U2 R' U R"
    ]
  },
  "F2L 35": {
    "FR": [
      "U' R U R' U F' U' F",
      "U' R U R' d R' U' R",
      "U2 R U R' F R' F' R",
      "U' R U R' U y' R' U' R"
    ],
    "FL": [
      "U2 F U F' U' L' U L",
      "U2 L F' L' F U2 L' U' L",
      "U' F R' F R F' U F'",
      "U' F U F' U L' U' L"
    ],
    "BL": [
      "U' L U L' U f' L' f",
      "U2 L U L' U' L F U F' L'",
      "L U L' y R' U' R U R' U' R",
      "U2 L U M U L' U' M'"
    ],
    "BR": [
      "U' f R f' U R' U' R",
      "R' F R' F' R U R U' R' U' R",
      "U2 f R f' U' R' U R",
      "U' R' F' U F U' R U R' U' R"
    ]
  },
  "F2L 36": {
    "FR": [
      "U F' U' F U' R U R'",
      "U2 R' F R F' U2 R U R'",
      "R U R' U R U R' U' F' U' F",
      "R2 u R U R' U' u' R' U R'"
    ],
    "FL": [
      "U L' U' L d' L U L'",
      "U L' U' L U' F U F'",
      "U2 L' U L U F U F'",
      "U2 L' U' L F' r U r'"
    ],
    "BL": [
      "U f' L' f U' L U L'",
      "U2 f' L' f U L U' L'",
      "L F' L F L' U' L' U L U L'",
      "y U R' U' R U' f R f'"
    ],
    "BR": [
      "U R' U' R U' f R f'",
      "U2 R' U' R U R' F' U' F R",
      "U R' U' R y U' R U R'",
      "U R' U' R U' y R U R'"
    ]
  },
  "F2L 37": {
    "FR": [
      "R2 U2 F R2 F' U2 R' U R'",
      "R' F R F' R U' R' U R U' R' U2 R U' R'",
      "R U2 R' U R U2 R' U F' U' F",
      "R U R' U2 R U2 R' U y' R' U' R"
    ],
    "FL": [
      "L2 U2 F' L2 F U2 L U' L",
      "L' U2 L U' L' U2 L U' F U F'",
      "L' U' L U2 L' U2 L U' y' R U R'",
      "R' F R L' U' L U' R' F R L' U' L"
    ],
    "BL": [
      "L U' L' l' U2 L2 U L2 U l",
      "f' L f U' L U2 L' U2 L U' L'",
      "L U2 L' U L U2 L' U f' L' f",
      "L' f U f' L' U2 L2 U L2 U L"
    ],
    "BR": [
      "R' U R r U2 R2 U' R2 U' r'",
      "R' U2 R U' R' U2 R U' f R f'",
      "R' U R f R U R2 U' R f'",
      "R' U' R U2 R' U2 R U' f R f'"
    ]
  },
  "F2L 38": {
    "FR": [
      "R U' R' U' R U R' U2 R U' R'",
      "R U R' U' R U2 R' U' R U R'",
      "R2 U2 R' U' R U' R' U2 R'",
      "R U' R' U' R U R' U' R U2 R'"
    ],
    "FL": [
      "L' U L U' L' U2 L U' L' U L",
      "F R U2 R' U' R U R' U2 F'",
      "L' U2 L' U' L U' L' U2 L2",
      "F U' R U2 R' U' R U2 R' F'"
    ],
    "BL": [
      "L U L' U' L U2 L' U' L U L'",
      "L2 U2 L' U' L U' L' U2 L'",
      "L U' L' U' L U L' U' L U2 L'",
      "L U' L' U' L U L' U2 L U' L'"
    ],
    "BR": [
      "R' U' R U2 R' U R U' R' U' R",
      "R' U R U' R' U2 R U' R' U R",
      "R' U2 R' U' R U' R' U2 R2"
    ]
  },
  "F2L 39": {
    "FR": [
      "R U' R' U R U2 R' U R U' R'",
      "R U2 R U R' U R U2 R2",
      "R U R' U2 R U' R' U R U R'",
      "R U2 R' U R U' R' U R U R'"
    ],
    "FL": [
      "L' U' L U L' U2 L U L' U' L",
      "F' L F L2 U2 L U L' U' L",
      "L' U L U L' U' L U2 L' U L",
      "F U2 R U' R' U R U2 R' F'"
    ],
    "BL": [
      "L U L' U2 L U' L' U L U L'",
      "L U' L' U L U2 L' U L U' L'",
      "L U2 L' U L U' L' U L U L'",
      "L U2 L U L' U L U2 L2"
    ],
    "BR": [
      "R' U' R U R' U2 R U R' U' R",
      "R' U R U R' U' R U2 R' U R",
      "f R2 U R' U' F R' f' U F'",
      "R2 U2 R U R' U R U2 R"
    ]
  },
  "F2L 40": {
    "FR": [
      "r U' r' U2 r U r' R U R'",
      "F' L' U2 L F R U R'",
      "R U' R' F R U R' U' F' R U' R'",
      "R U' R' U' R U' R' U y' R' U' R"
    ],
    "FL": [
      "L' U L F R U2 R' F'",
      "L' U L l' U l U2 l' U' l",
      "L' U L R' F R U2 R' F' R",
      "L' U L U2 y L U L' U L U' L'"
    ],
    "BL": [
      "l U' l' U2 l U l' L U L'",
      "f' L f L F U2 F' L'",
      "f' L f U2 L U L' U L U' L'",
      "f' L f U2 L U L' U2 L U2 L'"
    ],
    "BR": [
      "R' U R r' U r U2 r' U' r",
      "R' F' U2 F R f R f'",
      "R' U R f U R2 U' f'",
      "R2 F' U' F U R U' R"
    ]
  },
  "F2L 41": {
    "FR": [
      "R U' R' r U' r' U2 r U r'",
      "R U' R' F' L' U2 L F",
      "R U R' U' y M U' R' F R U M'",
      "R U R' U' R U' R' U2 y' R' U' R"
    ],
    "FL": [
      "l' U l U2 l' U' l L' U' L",
      "L' U L U L' U L U' y' R U R'",
      "F R U2 R' F' L' U' L",
      "R' F R U2 R' F' R L' U' L"
    ],
    "BL": [
      "f' L f U' L U L' U L U L'",
      "L2 F U F' U' L' U L'",
      "L F U2 F' L' f' L' f",
      "L U' L' d' U' R' U' R U' R' U R"
    ],
    "BR": [
      "r' U r U2 r' U' r R' U' R",
      "R' U R' U' F' U F R2",
      "f R' f' U2 R' U' R U' R' U R",
      "f R' f' U2 R' U' R U2 R' U2 R"
    ]
  }
};
