/**
 * Rebuild: node node_modules/vite-node/vite-node.mjs --script scripts/buildF2lThumbnailMap.ts
 * Append --check to verify the checked-in map without writing it.
 */
import assert from "node:assert/strict";
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { Alg } from "cubing/alg";
import type { KPuzzle } from "cubing/kpuzzle";
import { CENTER_FACELETS, CORNER_FACELETS, EDGE_FACELETS, patternToFacelets } from "../src/cube/facelets";
import { F2L_POSITIONS, type F2lPosition } from "../src/cube/f2lCases";
import { f2lTrainingCatalogue, type F2lTrainingCase, type F2lTrainingLibrary } from "../src/cube/f2lTrainingCases";
import { buildF2lCatalogueCaseState } from "../src/cube/f2lTraining";
import { f2lSlotsForCrossFace } from "../src/cube/moves";
import { get3x3x3 } from "../src/cube/puzzle";

/** Identify home cubies, then locate them after the physical display rotation. */
export function buildStoredF2lThumbnail(kpuzzle: KPuzzle, f2lCase: F2lTrainingCase, position: F2lPosition) {
  const state = buildF2lCatalogueCaseState(kpuzzle, f2lCase, position);
  const target = f2lSlotsForCrossFace("U").find((candidate) => candidate.name === state.slot);
  assert(target, `Missing target slot ${state.slot} for ${f2lCase.name} ${position}`);

  // Piece identities are HOME slot indices, never the occupants of an unsolved slot.
  const targetCornerPiece = target.corner;
  const targetEdgePiece = target.edge;
  const displayPattern = state.pattern.applyAlg(new Alg(state.trainingRotation.tokens.join(" ")));
  const displayedCornerSlot = displayPattern.patternData.CORNERS.pieces.indexOf(targetCornerPiece);
  const displayedEdgeSlot = displayPattern.patternData.EDGES.pieces.indexOf(targetEdgePiece);
  assert(displayedCornerSlot >= 0, `Missing target corner for ${f2lCase.name} ${position}`);
  assert(displayedEdgeSlot >= 0, `Missing target edge for ${f2lCase.name} ${position}`);

  const facelets = patternToFacelets(displayPattern);
  const emphasized = [
    ...CORNER_FACELETS[displayedCornerSlot],
    ...EDGE_FACELETS[displayedEdgeSlot],
    ...CENTER_FACELETS,
  ].sort((a, b) => a - b);
  assert.equal(facelets.length, 54);
  assert.equal(emphasized.length, 11);
  assert.equal(new Set(emphasized).size, 11, `Invalid emphasis for ${f2lCase.name} ${position}`);
  assert(emphasized.every((index) => Number.isInteger(index) && index >= 0 && index < 54));
  return { facelets, emphasized };
}

export function renderF2lThumbnailMap(kpuzzle: KPuzzle, library: F2lTrainingLibrary = "basic"): string {
  const cases = f2lTrainingCatalogue(library).cases;
  assert.equal(cases.length, library === "basic" ? 41 : 54);
  assert.equal(F2L_POSITIONS.length, 4);
  const entries: string[] = [];
  let count = 0;
  for (const f2lCase of cases) {
    entries.push(`  ${JSON.stringify(f2lCase.name)}: {`);
    for (const position of F2L_POSITIONS) {
      const stored = buildStoredF2lThumbnail(kpuzzle, f2lCase, position);
      entries.push(`    ${position}: ${JSON.stringify(stored)},`);
      count++;
    }
    entries.push("  },");
  }
  assert.equal(count, library === "basic" ? 164 : 216);
  const types = library === "basic" ? [
    "export type StoredF2lThumbnail = {",
    "  facelets: string;",
    "  emphasized: readonly number[];",
    "};",
    "",
  ] : [];
  return [
    "// Generated by scripts/buildF2lThumbnailMap.ts. Do not edit by hand.",
    'import type { F2lPosition } from "./f2lCases";',
    ...(library === "advanced" ? ['import type { StoredF2lThumbnail } from "./f2lThumbnailMap.generated";'] : []),
    "",
    ...types,
    `export const ${library === "basic" ? "F2L_THUMBNAIL_MAP" : "ADVANCED_F2L_THUMBNAIL_MAP"}: Readonly<Record<string, Readonly<Record<F2lPosition, StoredF2lThumbnail>>>> = {`,
    ...entries,
    "};",
    "",
  ].join("\n");
}

// Importing the generator for semantic tests never writes the map.
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const kpuzzle = await get3x3x3();
  for (const library of ["basic", "advanced"] as const) {
    const filename = library === "basic" ? "f2lThumbnailMap.generated.ts" : "advancedF2lThumbnailMap.generated.ts";
    const output = new URL(`../src/cube/${filename}`, import.meta.url);
    const source = renderF2lThumbnailMap(kpuzzle, library);
    if (process.argv.includes("--check")) {
      assert.equal(readFileSync(output, "utf8").replace(/\r\n/g, "\n"), source, `${library} F2L thumbnail map is stale; regenerate it`);
      console.log(`${library} F2L thumbnail map is current (${library === "basic" ? 164 : 216} entries).`);
    } else {
      writeFileSync(output, source, "utf8");
      console.log(`Generated ${library} F2L thumbnail map (${library === "basic" ? 164 : 216} entries).`);
    }
  }
}
